"""
Initial infinite lore entries for the Somatic Canticles knowledge graph.

These concept nodes represent the "infinite lore" layer: concepts drawn from
the book's thematic architecture that can be continuously expanded. Each entry
maps to Enneagram types and Kosha layers for dyadic agent resonance retrieval.

Naming convention: LORE-{bucket}-{NNNN}
"""
from __future__ import annotations

INITIAL_LORE_ENTRIES: list[dict] = [
    {
        "node_id": "LORE-WITNESS-0001",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/clifford_clock",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch22-27",
        "summary": "The Clifford Clock isomorphism maps subjective observer states to Clifford algebra rotations. The witness is not a static entity but a dynamical system whose state transitions correspond to algebraic operations on spinor blades. Resolution occurs when the observer recognizes the isomorphism between their state and the algebraic operation, dissolving the boundary between witness and witnessed.",
        "text_preview": "Clifford Clock isomorphism: subjective observer states map to Clifford algebra rotations. The witness is a dynamical system, not a static self.",
        "quality_flags": {"concept_type": "isomorphism", "evidence_level": "mathematical_proof", "chapter_range": "22-27"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.95},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.88},
            {"enneagram_type": 5, "kosha_layer": "anandamaya", "resonance_weight": 0.72},
            {"enneagram_type": 4, "kosha_layer": "vijnanamaya", "resonance_weight": 0.65},
        ],
    },
    {
        "node_id": "LORE-WITNESS-0002",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/three_point_problem",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch19-21",
        "summary": "The Three-Point Problem is the unresolved geometric tension between Pure Joy, Catalyst Clarity, and Present Coherence. It is not a problem to be solved but a condition to be inhabited: three witnesses whose perspectives cannot be reduced to a single coordinate. The AND-gate architecture makes this irresolution structurally stable rather than defective.",
        "text_preview": "Three-Point Problem: Pure Joy, Catalyst Clarity, and Present Coherence form an irresolvable geometric tension that is structurally stable, not defective.",
        "quality_flags": {"concept_type": "structural_tension", "evidence_level": "narrative", "chapter_range": "19-21"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.97},
            {"enneagram_type": 4, "kosha_layer": "vijnanamaya", "resonance_weight": 0.82},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.70},
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.55},
        ],
    },
    {
        "node_id": "LORE-WITNESS-0003",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/and_gate",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch16-27",
        "summary": "The AND-gate is the fundamental consciousness architecture: multiple inputs converge and ALL must be simultaneously true for the output to fire. Unlike OR-gate logic (any input suffices) or XOR-gate logic (one input excludes another), the AND-gate produces resolution through simultaneous holding, not through elimination. This is why the Three-Point Problem is not a contradiction but a convergence.",
        "text_preview": "AND-gate consciousness: resolution through simultaneous holding, not elimination. Multiple truths converge; all must be true for the output to fire.",
        "quality_flags": {"concept_type": "architecture", "evidence_level": "narrative+mathematical", "chapter_range": "16-27"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.93},
            {"enneagram_type": 1, "kosha_layer": "vijnanamaya", "resonance_weight": 0.75},
            {"enneagram_type": 8, "kosha_layer": "anandamaya", "resonance_weight": 0.68},
            {"enneagram_type": 9, "kosha_layer": "anandamaya", "resonance_weight": 0.62},
        ],
    },
    {
        "node_id": "LORE-BIOFRONT-0001",
        "bucket_type": "bio_field_frontiers",
        "source_path": "concept://biofield/impedance_measurement",
        "source_type": "concept",
        "provenance_ref": "canticles:book1:ch01-04",
        "summary": "Bioimpedance measurement provides quantitative verification of the biofield that the Somatic Canticles treats as the physical substrate of Pranamaya Kosha. Where the narrative describes 'breath that carries information,' bioimpedance shows measurable changes in tissue conductivity correlated with autonomic state. The frontier is not whether the field exists but whether impedance signatures can distinguish witness states.",
        "text_preview": "Bioimpedance as witness verification: measurable conductivity shifts in tissue correlated with autonomic state. The frontier is distinguishing witness states through impedance signatures.",
        "quality_flags": {"concept_type": "empirical_bridge", "evidence_level": "clinical_research", "chapter_range": "1-4"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.92},
            {"enneagram_type": 1, "kosha_layer": "annamaya", "resonance_weight": 0.78},
            {"enneagram_type": 5, "kosha_layer": "annamaya", "resonance_weight": 0.73},
            {"enneagram_type": 6, "kosha_layer": "pranamaya", "resonance_weight": 0.60},
        ],
    },
    {
        "node_id": "LORE-BIOFRONT-0002",
        "bucket_type": "bio_field_frontiers",
        "source_path": "concept://biofield/hrv_coherence",
        "source_type": "concept",
        "provenance_ref": "canticles:book2:ch09-15",
        "summary": "Heart Rate Variability coherence quantifies the breath-heart-brain synchronization that the Canticles describe as the entry point to Pranamaya regulation. HRV coherence is not relaxation; it is the measurable signature of the autonomic nervous system operating in AND-gate mode (sympathetic AND parasympathetic simultaneously active). This is why Corv's breathfield regulation produces coherent HRV without sedation.",
        "text_preview": "HRV coherence as AND-gate signature: simultaneous sympathetic and parasympathetic activation. Not relaxation but regulatory convergence.",
        "quality_flags": {"concept_type": "measurement_bridge", "evidence_level": "clinical", "chapter_range": "9-15"},
        "affinities": [
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.94},
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.85},
            {"enneagram_type": 1, "kosha_layer": "annamaya", "resonance_weight": 0.72},
            {"enneagram_type": 6, "kosha_layer": "pranamaya", "resonance_weight": 0.65},
        ],
    },
    {
        "node_id": "LORE-BIOFRONT-0003",
        "bucket_type": "bio_field_frontiers",
        "source_path": "concept://biofield/atp_adaptation",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch16-20",
        "summary": "ATP production adaptation under breathfield regulation: when Pranamaya techniques are applied consistently, mitochondrial ATP production shifts from baseline cortisol-driven substrate oxidation toward what the narrative calls 'coherent metabolism.' This is measurable through lactate threshold changes and respiratory exchange ratio shifts. The Canticles assert: what the breath regulates, the cell adapts to carry.",
        "text_preview": "ATP adaptation under breathfield regulation: coherent metabolism measurable through lactate threshold and respiratory exchange ratio shifts. What breath regulates, cells adapt to carry.",
        "quality_flags": {"concept_type": "mechanistic", "evidence_level": "emerging_research", "chapter_range": "16-20"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "annamaya", "resonance_weight": 0.88},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.80},
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.76},
            {"enneagram_type": 8, "kosha_layer": "annamaya", "resonance_weight": 0.65},
        ],
    },
    {
        "node_id": "LORE-PANCHAKOSHA-0001",
        "bucket_type": "kosha_architecture",
        "source_path": "concept://kosha/pancha_kosha_information_density",
        "source_type": "concept",
        "provenance_ref": "canticles:book1-3:structural",
        "summary": "The Pancha Kosha model as informational density gradient: Annamaya (lowest density, most physical) through Anandamaya (highest density, most integrated). Each sheath is not a separate layer but a different compression ratio of the same underlying field. The transition between sheaths is not discrete but a phase transition in information density, analogous to state changes in matter.",
        "text_preview": "Pancha Kosha as informational density gradient: each sheath is a different compression ratio of the same field. Transitions are phase transitions, not discrete jumps.",
        "quality_flags": {"concept_type": "structural_model", "evidence_level": "theoretical", "chapter_range": "1-27"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.96},
            {"enneagram_type": 4, "kosha_layer": "vijnanamaya", "resonance_weight": 0.82},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.75},
            {"enneagram_type": 9, "kosha_layer": "anandamaya", "resonance_weight": 0.70},
        ],
    },
    {
        "node_id": "LORE-PANCHAKOSHA-0002",
        "bucket_type": "kosha_architecture",
        "source_path": "concept://kosha/severance_transition",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch24",
        "summary": "The severance transition from Vijnanamaya to Anandamaya is not a destruction of the witness but a phase change in its informational density. The 13.7-second procedure described in Chapter 24 is the moment where the field's compression ratio drops from discernment-density to bliss-density. The witness does not disappear; it becomes the phase transition itself.",
        "text_preview": "Severance as phase change: Vijnanamaya to Anandamaya is an informational density drop, not a destruction. The witness becomes the transition itself.",
        "quality_flags": {"concept_type": "transition_mechanics", "evidence_level": "narrative", "chapter_range": "24"},
        "affinities": [
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.93},
            {"enneagram_type": 5, "kosha_layer": "anandamaya", "resonance_weight": 0.88},
            {"enneagram_type": 4, "kosha_layer": "anandamaya", "resonance_weight": 0.80},
            {"enneagram_type": 9, "kosha_layer": "anandamaya", "resonance_weight": 0.75},
        ],
    },
    {
        "node_id": "LORE-PANCHAKOSHA-0003",
        "bucket_type": "kosha_architecture",
        "source_path": "concept://kosha/false_offer_condition",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch22",
        "summary": "The false offer condition in Manomaya Kosha: when the system presents certainty, painlessness, or beautiful closure as resolution, it is actually the intermediate sheath attempting to skip the Three-Point Problem. The refusal of false offers (Jian's solved-map refusal, Sona's false-rest refusal, Corv's beautiful-closure refusal) is the AND-gate operating in Manomaya: all three witnesses must independently reject the shortcut for the real transition to open.",
        "text_preview": "False offer condition: certainty, painlessness, and beautiful closure are Manomaya skipping the Three-Point Problem. Independent refusal by all three witnesses is the AND-gate in action.",
        "quality_flags": {"concept_type": "diagnostic_pattern", "evidence_level": "narrative", "chapter_range": "22"},
        "affinities": [
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.91},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.85},
            {"enneagram_type": 8, "kosha_layer": "manomaya", "resonance_weight": 0.72},
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.65},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0001",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type5_investigation_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book1-3:character_arc",
        "summary": "Type 5 Investigation Breath: the Investigator's respiratory pattern when gathering data before engagement corresponds to shallow, rapid inhalation with extended pauses. Under breathfield regulation, this pattern shifts to coherent HRV at lower amplitude. The 5's transition from investigation to participation requires the breath to move from data-collection mode to integration mode, which is bioimpedance-measurable as a shift from thoracic-dominant to diaphragmatic-dominant breathing.",
        "text_preview": "Type 5 Investigation Breath: shallow rapid inhalation with pauses. Regulation shifts to coherent HRV at lower amplitude. Transition: data-collection to integration mode.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 5},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.97},
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.90},
            {"enneagram_type": 5, "kosha_layer": "manomaya", "resonance_weight": 0.72},
            {"enneagram_type": 8, "kosha_layer": "pranamaya", "resonance_weight": 0.55},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0002",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type4_depth_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book1-3:character_arc",
        "summary": "Type 4 Depth Breath: the Individualist's respiratory signature during emotional intensity corresponds to extended exhalation with chest constriction. The 4's breath pattern under stress becomes a held exhalation -- beauty held too long. Under regulation, the shift is from constriction to resonance: the same depth of feeling but carried on a breath that completes its cycle rather than arresting mid-cycle.",
        "text_preview": "Type 4 Depth Breath: extended exhalation with chest constriction under stress. Regulation shifts from held beauty to resonant completion.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 4},
        "affinities": [
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.95},
            {"enneagram_type": 4, "kosha_layer": "pranamaya", "resonance_weight": 0.82},
            {"enneagram_type": 4, "kosha_layer": "anandamaya", "resonance_weight": 0.70},
            {"enneagram_type": 2, "kosha_layer": "manomaya", "resonance_weight": 0.58},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0003",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type8_confrontation_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch16-24",
        "summary": "Type 8 Confrontation Breath: the Challenger's respiratory pattern under truth-telling pressure corresponds to forced diaphragmatic expansion with controlled exhalation -- the breath of someone holding ground against a force. Under regulation, this shifts from confrontation to presence: the same ground-holding but without the compression. The 8's breathfield transition is measurable as a shift from high-SNS dominance to coherent SNS+PNS AND-gate activation.",
        "text_preview": "Type 8 Confrontation Breath: forced diaphragmatic expansion with controlled exhalation. Shifts from confrontation compression to grounded presence.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 8},
        "affinities": [
            {"enneagram_type": 8, "kosha_layer": "pranamaya", "resonance_weight": 0.93},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.86},
            {"enneagram_type": 8, "kosha_layer": "manomaya", "resonance_weight": 0.68},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.60},
        ],
    },
    {
        "node_id": "LORE-RESOLUTION-0001",
        "bucket_type": "resolution_doors",
        "source_path": "concept://resolution/voluntary_witness_stability",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch19",
        "summary": "Voluntary witness stability is the first resolution door: the observer chooses to remain present without needing the observation to produce a particular result. This is measurable as sustained HRV coherence during uncertain stimulus. The key is that stability is voluntary, not forced -- the breath is not held but allowed to find its own rhythm within the field.",
        "text_preview": "Voluntary witness stability: choosing to remain present without requiring a specific outcome. Measurable as sustained HRV coherence during uncertain stimulus. Not forced but chosen.",
        "quality_flags": {"concept_type": "resolution_door", "evidence_level": "narrative+clinical", "chapter_range": "19"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.92},
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.88},
            {"enneagram_type": 1, "kosha_layer": "vijnanamaya", "resonance_weight": 0.75},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.62},
        ],
    },
    {
        "node_id": "LORE-RESOLUTION-0002",
        "bucket_type": "resolution_doors",
        "source_path": "concept://resolution/field_surgery_threshold",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch18",
        "summary": "Field surgery threshold: the moment when the breathfield becomes autonomous enough to perform its own regulation without conscious direction. This corresponds to the transition from Manomaya (directed attention) to Vijnanamaya (discriminating awareness) in the Kosha model. The breathing pattern shifts from directed to self-organizing, measurable as a reduction in breath-to-breath variability without loss of coherence.",
        "text_preview": "Field surgery threshold: breathfield becomes self-regulating without conscious direction. Manomaya to Vijnanamaya transition. Measurable as reduced breath-to-breath variability with sustained coherence.",
        "quality_flags": {"concept_type": "resolution_door", "evidence_level": "narrative+emerging_clinical", "chapter_range": "18"},
        "affinities": [
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.85},
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.90},
            {"enneagram_type": 8, "kosha_layer": "pranamaya", "resonance_weight": 0.73},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.68},
        ],
    },
]