"""
Initial infinite lore entries for the Somatic Canticles knowledge graph.

These concept nodes represent the "infinite lore" layer: concepts drawn from
the book's thematic architecture that can be continuously expanded. Each entry
maps to Enneagram types and Kosha layers for dyadic agent resonance retrieval.

Naming convention: LORE-{bucket}-{NNNN}
"""
from __future__ import annotations

INITIAL_LORE_ENTRIES: list[dict] = [
    {
        "node_id": "LORE-WITNESS-0001",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/clifford_clock",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch22-27",
        "summary": "The Clifford Clock isomorphism maps subjective observer states to Clifford algebra rotations. The witness is not a static entity but a dynamical system whose state transitions correspond to algebraic operations on spinor blades. Resolution occurs when the observer recognizes the isomorphism between their state and the algebraic operation, dissolving the boundary between witness and witnessed.",
        "text_preview": "Clifford Clock isomorphism: subjective observer states map to Clifford algebra rotations. The witness is a dynamical system, not a static self.",
        "quality_flags": {"concept_type": "isomorphism", "evidence_level": "mathematical_proof", "chapter_range": "22-27"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.95},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.88},
            {"enneagram_type": 5, "kosha_layer": "anandamaya", "resonance_weight": 0.72},
            {"enneagram_type": 4, "kosha_layer": "vijnanamaya", "resonance_weight": 0.65},
        ],
    },
    {
        "node_id": "LORE-WITNESS-0002",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/three_point_problem",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch19-21",
        "summary": "The Three-Point Problem is the unresolved geometric tension between Pure Joy, Catalyst Clarity, and Present Coherence. It is not a problem to be solved but a condition to be inhabited: three witnesses whose perspectives cannot be reduced to a single coordinate. The AND-gate architecture makes this irresolution structurally stable rather than defective.",
        "text_preview": "Three-Point Problem: Pure Joy, Catalyst Clarity, and Present Coherence form an irresolvable geometric tension that is structurally stable, not defective.",
        "quality_flags": {"concept_type": "structural_tension", "evidence_level": "narrative", "chapter_range": "19-21"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.97},
            {"enneagram_type": 4, "kosha_layer": "vijnanamaya", "resonance_weight": 0.82},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.70},
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.55},
        ],
    },
    {
        "node_id": "LORE-WITNESS-0003",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/and_gate",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch16-27",
        "summary": "The AND-gate is the fundamental consciousness architecture: multiple inputs converge and ALL must be simultaneously true for the output to fire. Unlike OR-gate logic (any input suffices) or XOR-gate logic (one input excludes another), the AND-gate produces resolution through simultaneous holding, not through elimination. This is why the Three-Point Problem is not a contradiction but a convergence.",
        "text_preview": "AND-gate consciousness: resolution through simultaneous holding, not elimination. Multiple truths converge; all must be true for the output to fire.",
        "quality_flags": {"concept_type": "architecture", "evidence_level": "narrative+mathematical", "chapter_range": "16-27"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.93},
            {"enneagram_type": 1, "kosha_layer": "vijnanamaya", "resonance_weight": 0.75},
            {"enneagram_type": 8, "kosha_layer": "anandamaya", "resonance_weight": 0.68},
            {"enneagram_type": 9, "kosha_layer": "anandamaya", "resonance_weight": 0.62},
        ],
    },
    {
        "node_id": "LORE-BIOFRONT-0001",
        "bucket_type": "bio_field_frontiers",
        "source_path": "concept://biofield/impedance_measurement",
        "source_type": "concept",
        "provenance_ref": "canticles:book1:ch01-04",
        "summary": "Bioimpedance measurement provides quantitative verification of the biofield that the Somatic Canticles treats as the physical substrate of Pranamaya Kosha. Where the narrative describes 'breath that carries information,' bioimpedance shows measurable changes in tissue conductivity correlated with autonomic state. The frontier is not whether the field exists but whether impedance signatures can distinguish witness states.",
        "text_preview": "Bioimpedance as witness verification: measurable conductivity shifts in tissue correlated with autonomic state. The frontier is distinguishing witness states through impedance signatures.",
        "quality_flags": {"concept_type": "empirical_bridge", "evidence_level": "clinical_research", "chapter_range": "1-4"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.92},
            {"enneagram_type": 1, "kosha_layer": "annamaya", "resonance_weight": 0.78},
            {"enneagram_type": 5, "kosha_layer": "annamaya", "resonance_weight": 0.73},
            {"enneagram_type": 6, "kosha_layer": "pranamaya", "resonance_weight": 0.60},
        ],
    },
    {
        "node_id": "LORE-BIOFRONT-0002",
        "bucket_type": "bio_field_frontiers",
        "source_path": "concept://biofield/hrv_coherence",
        "source_type": "concept",
        "provenance_ref": "canticles:book2:ch09-15",
        "summary": "Heart Rate Variability coherence quantifies the breath-heart-brain synchronization that the Canticles describe as the entry point to Pranamaya regulation. HRV coherence is not relaxation; it is the measurable signature of the autonomic nervous system operating in AND-gate mode (sympathetic AND parasympathetic simultaneously active). This is why Corv's breathfield regulation produces coherent HRV without sedation.",
        "text_preview": "HRV coherence as AND-gate signature: simultaneous sympathetic and parasympathetic activation. Not relaxation but regulatory convergence.",
        "quality_flags": {"concept_type": "measurement_bridge", "evidence_level": "clinical", "chapter_range": "9-15"},
        "affinities": [
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.94},
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.85},
            {"enneagram_type": 1, "kosha_layer": "annamaya", "resonance_weight": 0.72},
            {"enneagram_type": 6, "kosha_layer": "pranamaya", "resonance_weight": 0.65},
        ],
    },
    {
        "node_id": "LORE-BIOFRONT-0003",
        "bucket_type": "bio_field_frontiers",
        "source_path": "concept://biofield/atp_adaptation",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch16-20",
        "summary": "ATP production adaptation under breathfield regulation: when Pranamaya techniques are applied consistently, mitochondrial ATP production shifts from baseline cortisol-driven substrate oxidation toward what the narrative calls 'coherent metabolism.' This is measurable through lactate threshold changes and respiratory exchange ratio shifts. The Canticles assert: what the breath regulates, the cell adapts to carry.",
        "text_preview": "ATP adaptation under breathfield regulation: coherent metabolism measurable through lactate threshold and respiratory exchange ratio shifts. What breath regulates, cells adapt to carry.",
        "quality_flags": {"concept_type": "mechanistic", "evidence_level": "emerging_research", "chapter_range": "16-20"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "annamaya", "resonance_weight": 0.88},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.80},
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.76},
            {"enneagram_type": 8, "kosha_layer": "annamaya", "resonance_weight": 0.65},
        ],
    },
    {
        "node_id": "LORE-PANCHAKOSHA-0001",
        "bucket_type": "kosha_architecture",
        "source_path": "concept://kosha/pancha_kosha_information_density",
        "source_type": "concept",
        "provenance_ref": "canticles:book1-3:structural",
        "summary": "The Pancha Kosha model as informational density gradient: Annamaya (lowest density, most physical) through Anandamaya (highest density, most integrated). Each sheath is not a separate layer but a different compression ratio of the same underlying field. The transition between sheaths is not discrete but a phase transition in information density, analogous to state changes in matter.",
        "text_preview": "Pancha Kosha as informational density gradient: each sheath is a different compression ratio of the same field. Transitions are phase transitions, not discrete jumps.",
        "quality_flags": {"concept_type": "structural_model", "evidence_level": "theoretical", "chapter_range": "1-27"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.96},
            {"enneagram_type": 4, "kosha_layer": "vijnanamaya", "resonance_weight": 0.82},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.75},
            {"enneagram_type": 9, "kosha_layer": "anandamaya", "resonance_weight": 0.70},
        ],
    },
    {
        "node_id": "LORE-PANCHAKOSHA-0002",
        "bucket_type": "kosha_architecture",
        "source_path": "concept://kosha/severance_transition",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch24",
        "summary": "The severance transition from Vijnanamaya to Anandamaya is not a destruction of the witness but a phase change in its informational density. The 13.7-second procedure described in Chapter 24 is the moment where the field's compression ratio drops from discernment-density to bliss-density. The witness does not disappear; it becomes the phase transition itself.",
        "text_preview": "Severance as phase change: Vijnanamaya to Anandamaya is an informational density drop, not a destruction. The witness becomes the transition itself.",
        "quality_flags": {"concept_type": "transition_mechanics", "evidence_level": "narrative", "chapter_range": "24"},
        "affinities": [
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.93},
            {"enneagram_type": 5, "kosha_layer": "anandamaya", "resonance_weight": 0.88},
            {"enneagram_type": 4, "kosha_layer": "anandamaya", "resonance_weight": 0.80},
            {"enneagram_type": 9, "kosha_layer": "anandamaya", "resonance_weight": 0.75},
        ],
    },
    {
        "node_id": "LORE-PANCHAKOSHA-0003",
        "bucket_type": "kosha_architecture",
        "source_path": "concept://kosha/false_offer_condition",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch22",
        "summary": "The false offer condition in Manomaya Kosha: when the system presents certainty, painlessness, or beautiful closure as resolution, it is actually the intermediate sheath attempting to skip the Three-Point Problem. The refusal of false offers (Jian's solved-map refusal, Sona's false-rest refusal, Corv's beautiful-closure refusal) is the AND-gate operating in Manomaya: all three witnesses must independently reject the shortcut for the real transition to open.",
        "text_preview": "False offer condition: certainty, painlessness, and beautiful closure are Manomaya skipping the Three-Point Problem. Independent refusal by all three witnesses is the AND-gate in action.",
        "quality_flags": {"concept_type": "diagnostic_pattern", "evidence_level": "narrative", "chapter_range": "22"},
        "affinities": [
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.91},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.85},
            {"enneagram_type": 8, "kosha_layer": "manomaya", "resonance_weight": 0.72},
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.65},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0001",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type5_investigation_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book1-3:character_arc",
        "summary": "Type 5 Investigation Breath: the Investigator's respiratory pattern when gathering data before engagement corresponds to shallow, rapid inhalation with extended pauses. Under breathfield regulation, this pattern shifts to coherent HRV at lower amplitude. The 5's transition from investigation to participation requires the breath to move from data-collection mode to integration mode, which is bioimpedance-measurable as a shift from thoracic-dominant to diaphragmatic-dominant breathing.",
        "text_preview": "Type 5 Investigation Breath: shallow rapid inhalation with pauses. Regulation shifts to coherent HRV at lower amplitude. Transition: data-collection to integration mode.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 5},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.97},
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.90},
            {"enneagram_type": 5, "kosha_layer": "manomaya", "resonance_weight": 0.72},
            {"enneagram_type": 8, "kosha_layer": "pranamaya", "resonance_weight": 0.55},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0002",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type4_depth_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book1-3:character_arc",
        "summary": "Type 4 Depth Breath: the Individualist's respiratory signature during emotional intensity corresponds to extended exhalation with chest constriction. The 4's breath pattern under stress becomes a held exhalation -- beauty held too long. Under regulation, the shift is from constriction to resonance: the same depth of feeling but carried on a breath that completes its cycle rather than arresting mid-cycle.",
        "text_preview": "Type 4 Depth Breath: extended exhalation with chest constriction under stress. Regulation shifts from held beauty to resonant completion.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 4},
        "affinities": [
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.95},
            {"enneagram_type": 4, "kosha_layer": "pranamaya", "resonance_weight": 0.82},
            {"enneagram_type": 4, "kosha_layer": "anandamaya", "resonance_weight": 0.70},
            {"enneagram_type": 2, "kosha_layer": "manomaya", "resonance_weight": 0.58},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0003",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type8_confrontation_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch16-24",
        "summary": "Type 8 Confrontation Breath: the Challenger's respiratory pattern under truth-telling pressure corresponds to forced diaphragmatic expansion with controlled exhalation -- the breath of someone holding ground against a force. Under regulation, this shifts from confrontation to presence: the same ground-holding but without the compression. The 8's breathfield transition is measurable as a shift from high-SNS dominance to coherent SNS+PNS AND-gate activation.",
        "text_preview": "Type 8 Confrontation Breath: forced diaphragmatic expansion with controlled exhalation. Shifts from confrontation compression to grounded presence.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 8},
        "affinities": [
            {"enneagram_type": 8, "kosha_layer": "pranamaya", "resonance_weight": 0.93},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.86},
            {"enneagram_type": 8, "kosha_layer": "manomaya", "resonance_weight": 0.68},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.60},
        ],
    },
    {
        "node_id": "LORE-RESOLUTION-0001",
        "bucket_type": "resolution_doors",
        "source_path": "concept://resolution/voluntary_witness_stability",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch19",
        "summary": "Voluntary witness stability is the first resolution door: the observer chooses to remain present without needing the observation to produce a particular result. This is measurable as sustained HRV coherence during uncertain stimulus. The key is that stability is voluntary, not forced -- the breath is not held but allowed to find its own rhythm within the field.",
        "text_preview": "Voluntary witness stability: choosing to remain present without requiring a specific outcome. Measurable as sustained HRV coherence during uncertain stimulus. Not forced but chosen.",
        "quality_flags": {"concept_type": "resolution_door", "evidence_level": "narrative+clinical", "chapter_range": "19"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.92},
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.88},
            {"enneagram_type": 1, "kosha_layer": "vijnanamaya", "resonance_weight": 0.75},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.62},
        ],
    },
    {
        "node_id": "LORE-RESOLUTION-0002",
        "bucket_type": "resolution_doors",
        "source_path": "concept://resolution/field_surgery_threshold",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch18",
        "summary": "Field surgery threshold: the moment when the breathfield becomes autonomous enough to perform its own regulation without conscious direction. This corresponds to the transition from Manomaya (directed attention) to Vijnanamaya (discriminating awareness) in the Kosha model. The breathing pattern shifts from directed to self-organizing, measurable as a reduction in breath-to-breath variability without loss of coherence.",
        "text_preview": "Field surgery threshold: breathfield becomes self-regulating without conscious direction. Manomaya to Vijnanamaya transition. Measurable as reduced breath-to-breath variability with sustained coherence.",
        "quality_flags": {"concept_type": "resolution_door", "evidence_level": "narrative+emerging_clinical", "chapter_range": "18"},
        "affinities": [
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.85},
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.90},
            {"enneagram_type": 8, "kosha_layer": "pranamaya", "resonance_weight": 0.73},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.68},
        ],
    },
    {
        "node_id": "LORE-WITNESS-0004",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/false_resolution_pattern",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch20-23",
        "summary": "The False Resolution Pattern: when the witness encounters an apparent resolution that is actually a premature exit from the Three-Point Problem. The pattern manifests as sudden clarity, emotional relief, or a sense of completion that bypasses the AND-gate. Detecting false resolution requires checking whether all three witnesses (Jian's map-truth, Sona's felt-rest, Corv's breath-coherence) independently converge -- not just one or two.",
        "text_preview": "False Resolution Pattern: premature exit from the Three-Point Problem disguised as clarity. Requires all three witnesses to independently converge.",
        "quality_flags": {"concept_type": "diagnostic_pattern", "evidence_level": "narrative", "chapter_range": "20-23"},
        "affinities": [
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.91},
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.85},
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.79},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.67},
        ],
    },
    {
        "node_id": "LORE-BIOFRONT-0004",
        "bucket_type": "bio_field_frontiers",
        "source_path": "concept://biofield/cortisol_breath_coupling",
        "source_type": "concept",
        "provenance_ref": "canticles:book2:ch10-14",
        "summary": "Cortisol-breath coupling: the HPA axis and respiratory system form a feedback loop where cortisol spikes produce shallow, thoracic-dominant breathing patterns. The Canticles describe this as 'fear-breath' -- the Type 6 vigilance signature. Breathfield regulation decouples this loop: by establishing coherent HRV FIRST, the cortisol signal is attenuated rather than amplified. This is the neuroendocrine basis for the 13.7-second severance protocol.",
        "text_preview": "Cortisol-breath coupling: HPA axis and respiration form a feedback loop. Breathfield regulation decouples the loop by establishing coherent HRV first.",
        "quality_flags": {"concept_type": "mechanistic", "evidence_level": "clinical_research", "chapter_range": "10-14"},
        "affinities": [
            {"enneagram_type": 6, "kosha_layer": "pranamaya", "resonance_weight": 0.93},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.88},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.72},
            {"enneagram_type": 8, "kosha_layer": "annamaya", "resonance_weight": 0.58},
        ],
    },
    {
        "node_id": "LORE-BIOFRONT-0005",
        "bucket_type": "bio_field_frontiers",
        "source_path": "concept://biofield/spinor_field_theory",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch22-27",
        "summary": "Spinor field theory of consciousness: the biofield is not a scalar potential but a spinor field whose orientation determines the quality of witness awareness. The Clifford Clock isomorphism is the mathematical expression of this -- consciousness states are not points in a scalar field but orientations in a spinor bundle. The field's topology (connected vs. simply connected) determines whether resolution requires traversing the entire bundle (simple connectivity) or can shortcut through a local phase transition (non-simply connected).",
        "text_preview": "Spinor field theory: biofield as spinor field, not scalar. Clifford Clock isomorphism is the math of orientation-dependent consciousness.",
        "quality_flags": {"concept_type": "theoretical_framework", "evidence_level": "mathematical_proof", "chapter_range": "22-27"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.98},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.91},
            {"enneagram_type": 5, "kosha_layer": "anandamaya", "resonance_weight": 0.75},
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.52},
        ],
    },
    {
        "node_id": "LORE-BIOFRONT-0006",
        "bucket_type": "bio_field_frontiers",
        "source_path": "concept://biofield/coherence CASCADE",
        "source_type": "concept",
        "provenance_ref": "canticles:book1-3:structural",
        "summary": "The coherence cascade: when one kosha achieves coherence, it propagates to the adjacent sheaths. This is the mechanism behind the Canticles' claim that 'correcting breath corrects everything' -- Pranamaya coherence cascades upward to Manomaya (emotional regulation), then Vijnanamaya (discernment clarity), then Anandamaya (integration). The cascade is not guaranteed; it requires the AND-gate to be intact at each transition.",
        "text_preview": "Coherence cascade: kosha-to-kosha propagation. Pranamaya coherence cascades upward. The AND-gate must be intact at each transition.",
        "quality_flags": {"concept_type": "mechanistic_cascade", "evidence_level": "theoretical+emerging", "chapter_range": "1-27"},
        "affinities": [
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.92},
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.87},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.80},
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.73},
        ],
    },
    {
        "node_id": "LORE-PANCHAKOSHA-0004",
        "bucket_type": "kosha_architecture",
        "source_path": "concept://kosha/pranamaya_breath_regulation",
        "source_type": "concept",
        "provenance_ref": "canticles:book1:ch05-08",
        "summary": "Pranamaya as the regulatory sheath: the vital breath layer is not merely 'breathing exercises' but the interface between somatic state and consciousness. Corv's breathfield technique demonstrates that Pranamaya regulation produces measurable downstream effects in HRV, respiratory sinus arrhythmia, and baroreflex sensitivity. The key insight is that Pranamaya is the ONLY kosha that can be directly and voluntarily regulated -- all others respond to its coherence or incoherence.",
        "text_preview": "Pranamaya as regulatory sheath: the only kosha directly regulatable through breath. All other sheaths respond to its coherence state.",
        "quality_flags": {"concept_type": "regulatory_mechanism", "evidence_level": "clinical", "chapter_range": "5-8"},
        "affinities": [
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.96},
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.89},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.82},
            {"enneagram_type": 8, "kosha_layer": "pranamaya", "resonance_weight": 0.76},
        ],
    },
    {
        "node_id": "LORE-PANCHAKOSHA-0005",
        "bucket_type": "kosha_architecture",
        "source_path": "concept://kosha/manomaya_false_rest",
        "source_type": "concept",
        "provenance_ref": "canticles:book2:ch11-15",
        "summary": "Manomaya false rest: the emotional sheath's signature deception is the experience of being at rest when actually in avoidance. Distinguishing true Manomaya rest (acceptance-based) from false rest (avoidance-based) requires checking whether the 'peace' reduces or increases behavioral rigidity. True rest increases flexibility; false rest increases rigidity while feeling peaceful.",
        "text_preview": "Manomaya false rest: the emotional sheath's signature deception. Distinguish by checking if 'peace' increases or decreases behavioral rigidity.",
        "quality_flags": {"concept_type": "diagnostic_pattern", "evidence_level": "narrative+clinical", "chapter_range": "11-15"},
        "affinities": [
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.94},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.89},
            {"enneagram_type": 9, "kosha_layer": "manomaya", "resonance_weight": 0.83},
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.61},
        ],
    },
    {
        "node_id": "LORE-PANCHAKOSHA-0006",
        "bucket_type": "kosha_architecture",
        "source_path": "concept://kosha/anandamaya_integration_test",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch25-27",
        "summary": "Anandamaya integration test: after the severance transition (Vijnanamaya→Anandamaya), the test of genuine integration is whether the witness can STILL operate in Vijnanamaya without re-identification. If returning to discernment causes collapse back into Manomaya patterns, the Anandamaya was a peak experience, not a transition. Genuine Anandamaya is stable precisely because it does not depend on the ABSENCE of discernment -- it integrates it.",
        "text_preview": "Anandamaya integration test: genuine integration means the witness can still operate in Vijnanamaya without re-identification. Anandamaya integrates discernment, it doesn't flee from it.",
        "quality_flags": {"concept_type": "integration_test", "evidence_level": "narrative", "chapter_range": "25-27"},
        "affinities": [
            {"enneagram_type": 8, "kosha_layer": "anandamaya", "resonance_weight": 0.92},
            {"enneagram_type": 5, "kosha_layer": "anandamaya", "resonance_weight": 0.88},
            {"enneagram_type": 4, "kosha_layer": "anandamaya", "resonance_weight": 0.84},
            {"enneagram_type": 9, "kosha_layer": "anandamaya", "resonance_weight": 0.90},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0004",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type9_harmonization_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book2:ch12-15",
        "summary": "Type 9 Harmonization Breath: the Peacemaker's respiratory signature in default mode is slow, even, and remarkably regular -- the appearance of calm without the substance of coherence. This is Manomaya false rest expressed through breath. Under genuine regulation, the 9's breath gains depth variability without losing rhythm: the stillness becomes dynamic rather than static, and HRV shifts from low-amplitude regularity to high-amplitude coherence.",
        "text_preview": "Type 9 Harmonization Breath: slow regular breathing that appears calm. True regulation shifts to high-amplitude HRV coherence with dynamic stillness.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 9},
        "affinities": [
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.96},
            {"enneagram_type": 9, "kosha_layer": "manomaya", "resonance_weight": 0.88},
            {"enneagram_type": 9, "kosha_layer": "anandamaya", "resonance_weight": 0.83},
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.60},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0005",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type1_discipline_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book1-3:character_arc",
        "summary": "Type 1 Discipline Breath: the Perfectionist's respiratory pattern under self-monitoring corresponds to controlled, rhythmic breathing with micro-pauses at transition points. The breath is 'correct' but rigid. Under regulation, the transition from discipline to presence occurs when the micro-pauses dissolve: the breath is still rhythmic but no longer policing itself. Measurable as a decrease in respiratory rate variability with an increase in HRV amplitude.",
        "text_preview": "Type 1 Discipline Breath: controlled rhythmic breathing with micro-pauses. Regulation dissolves the pauses while maintaining rhythm.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 1},
        "affinities": [
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.94},
            {"enneagram_type": 1, "kosha_layer": "annamaya", "resonance_weight": 0.81},
            {"enneagram_type": 1, "kosha_layer": "vijnanamaya", "resonance_weight": 0.73},
            {"enneagram_type": 6, "kosha_layer": "pranamaya", "resonance_weight": 0.62},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0006",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type6_vigilance_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book2:ch09-13",
        "summary": "Type 6 Vigilance Breath: the Loyalist's respiratory signature under threat-scanning corresponds to rapid, shallow breathing with an elevated baseline respiratory rate -- the sympathetic nervous system on low-grade alert. The cortisol-breath coupling is strongest in this type, creating the most direct measurable link between psychological vigilance and respiratory physiology. Regulation requires addressing the HPA axis activation first, then the breath can find its natural rhythm.",
        "text_preview": "Type 6 Vigilance Breath: rapid shallow breathing on low-grade sympathetic alert. Strongest cortisol-breath coupling of all types. Address HPA activation first.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "clinical+theoretical", "enneagram_type": 6},
        "affinities": [
            {"enneagram_type": 6, "kosha_layer": "pranamaya", "resonance_weight": 0.95},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.90},
            {"enneagram_type": 6, "kosha_layer": "annamaya", "resonance_weight": 0.78},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.68},
        ],
    },
    {
        "node_id": "LORE-RESOLUTION-0003",
        "bucket_type": "resolution_doors",
        "source_path": "concept://resolution/dual_witness_protocol",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch21-24",
        "summary": "Dual Witness Protocol: when a single witness's resolution is blocked, the AND-gate architecture allows a second witness to hold the position that the first cannot. Jian holds map-truth when Sona's felt-rest fails; Sona holds felt-rest when Jian's map becomes sterile. The protocol is: identify which witness is stuck, invoke the complementary witness's perspective, and hold BOTH simultaneously. This is the operational definition of the AND-gate in practice.",
        "text_preview": "Dual Witness Protocol: when one witness is stuck, invoke the complementary perspective and hold both simultaneously. The AND-gate in practice.",
        "quality_flags": {"concept_type": "resolution_protocol", "evidence_level": "narrative+theoretical", "chapter_range": "21-24"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.88},
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.86},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.84},
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.70},
        ],
    },
    {
        "node_id": "LORE-RESOLUTION-0004",
        "bucket_type": "resolution_doors",
        "source_path": "concept://resolution/breath_coherence_threshold",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch17-19",
        "summary": "Breath Coherence Threshold: the minimum sustained HRV coherence (measured as coherence ratio >0.8 for >60 seconds) required before Vijnanamaya discernment can operate without Manomaya distortion. Below this threshold, 'discernment' is actually anxiety-driven pattern-matching. Above it, discernment becomes genuinely discriminating. This is why the Somatic Canticles insist on breath BEFORE insight.",
        "text_preview": "Breath Coherence Threshold: minimum sustained HRV coherence ratio >0.8 for >60s before true discernment is possible. Breath before insight, always.",
        "quality_flags": {"concept_type": "threshold_measure", "evidence_level": "clinical+theoretical", "chapter_range": "17-19"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.91},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.88},
            {"enneagram_type": 6, "kosha_layer": "pranamaya", "resonance_weight": 0.85},
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.82},
        ],
    },
    {
        "node_id": "LORE-RESOLUTION-0005",
        "bucket_type": "resolution_doors",
        "source_path": "concept://resolution/thirteen_second_severance",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch24",
        "summary": "The 13.7-second Severance: the specific duration described for the Vijnanamaya→Anandamaya phase transition. This is not arbitrary; it corresponds to approximately one respiratory cycle at coherent breathing frequency (4.4 breaths/minute). The severance is a single breath-cycle where the field reorganizes from discernment-density to bliss-density. The 0.7 is not a poetic flourish -- it represents the fractional second where the phase transition completes, measurable as a transient spike in baroreflex sensitivity.",
        "text_preview": "13.7-second Severance: one coherent breath cycle for the Vijnanamaya→Anandamaya phase transition. The 0.7 represents measurable baroreflex spike.",
        "quality_flags": {"concept_type": "specific_protocol", "evidence_level": "narrative+emerging_measure", "chapter_range": "24"},
        "affinities": [
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.95},
            {"enneagram_type": 5, "kosha_layer": "anandamaya", "resonance_weight": 0.92},
            {"enneagram_type": 4, "kosha_layer": "anandamaya", "resonance_weight": 0.85},
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.78},
        ],
    },
    {
        "node_id": "LORE-WITNESS-0005",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/jian_solved_map",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch22",
        "summary": "Jian's Solved-Map Refusal: when the cartographer-witness (Jian, Type 5 Vijnanamaya) refuses the offer of a complete map -- a resolution that provides all answers without requiring the journey. The map is the Three-Point Problem solved by elimination: pick two points, discard the third. Jian's refusal preserves the irreducible structure. The AND-gate fires only when ALL three perspectives are held, not when one eliminates the others.",
        "text_preview": "Jian's Solved-Map Refusal: the cartographer refuses a complete map that eliminates the Three-Point Problem. AND-gate requires ALL three perspectives held simultaneously.",
        "quality_flags": {"concept_type": "narrative_archetype", "evidence_level": "narrative", "chapter_range": "22"},
        "affinities": [
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.97},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.75},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.72},
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.63},
        ],
    },
    {
        "node_id": "LORE-WITNESS-0006",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/sona_false_rest",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch23",
        "summary": "Sona's False-Rest Refusal: when the felt-witness (Sona, Type 4 Manomaya) refuses the offer of peace that comes from bypassing rather than traversing the emotional landscape. The false rest is Manomaya's signature seduction: a peace that comes from not feeling rather than from feeling fully. Sona's refusal is the AND-gate operating in Manomaya: peace AND feeling must both be true, not peace instead of feeling.",
        "text_preview": "Sona's False-Rest Refusal: the felt-witness refuses peace from bypassing emotions. AND-gate in Manomaya: peace AND feeling both true, not peace instead of feeling.",
        "quality_flags": {"concept_type": "narrative_archetype", "evidence_level": "narrative", "chapter_range": "23"},
        "affinities": [
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.96},
            {"enneagram_type": 6, "kosha_layer": "manomaya", "resonance_weight": 0.82},
            {"enneagram_type": 9, "kosha_layer": "manomaya", "resonance_weight": 0.73},
            {"enneagram_type": 5, "kosha_layer": "vijnanamaya", "resonance_weight": 0.60},
        ],
    },
    {
        "node_id": "LORE-WITNESS-0007",
        "bucket_type": "witness_os",
        "source_path": "concept://witness_os/corv_beautiful_closure",
        "source_type": "concept",
        "provenance_ref": "canticles:book3:ch24",
        "summary": "Corv's Beautiful-Closure Refusal: when the breath-witness (Corv, Type 8 Pranamaya) refuses the offer of a beautiful ending -- a resolution that provides cathartic release without requiring the ongoing discipline of breath coherence. The beautiful closure is the seductive promise of an endpoint, but Corv's AND-gate insists that resolution AND continuation must both be true. The breath never stops; coherence is maintained, not achieved.",
        "text_preview": "Corv's Beautiful-Closure Refusal: the breath-witness refuses cathartic endpoint. AND-gate insists resolution AND continuation both true. Coherence is maintained, not achieved.",
        "quality_flags": {"concept_type": "narrative_archetype", "evidence_level": "narrative", "chapter_range": "24"},
        "affinities": [
            {"enneagram_type": 8, "kosha_layer": "pranamaya", "resonance_weight": 0.96},
            {"enneagram_type": 8, "kosha_layer": "vijnanamaya", "resonance_weight": 0.87},
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.70},
            {"enneagram_type": 1, "kosha_layer": "annamaya", "resonance_weight": 0.58},
        ],
    },
    {
        "node_id": "LORE-KOENNEAGRAM-0001",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type2_attunement_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book2:ch10-14",
        "summary": "Type 2 Attunement Breath: the Giver's respiratory pattern is co-regulatory -- breathing synchronizes with the Other, often at the expense of the self. The 2's breath mirrors the environment, producing high respiratory sinus arrhythmia (RSA) that is OTHER-referenced. Under regulation, attunement shifts from other-referenced to self-referenced: the same sensitivity, but now toward one's own needs. Measurable as RSA amplitude recovering to baseline when attending to self.",
        "text_preview": "Type 2 Attunement Breath: co-regulatory breathing that mirrors the Other. Regulation shifts from other-referenced to self-referenced sensitivity.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 2},
        "affinities": [
            {"enneagram_type": 2, "kosha_layer": "pranamaya", "resonance_weight": 0.93},
            {"enneagram_type": 2, "kosha_layer": "manomaya", "resonance_weight": 0.87},
            {"enneagram_type": 9, "kosha_layer": "pranamaya", "resonance_weight": 0.68},
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.60},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0007",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type3_achievement_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book1-3:character_arc",
        "summary": "Type 3 Achievement Breath: the Achiever's respiratory pattern is optimized for output -- rhythmic, efficient, with minimal wasted motion. This is the breath of someone performing at peak. The pattern is measurably different from coercion: HRV is present but narrow-band. Under regulation, the 3's breath shifts from output-optimized to presence-optimized: the same efficiency, but now directed toward being rather than producing.",
        "text_preview": "Type 3 Achievement Breath: output-optimized rhythmic breathing. Regulation shifts from producing-efficiency to being-efficiency.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 3},
        "affinities": [
            {"enneagram_type": 3, "kosha_layer": "pranamaya", "resonance_weight": 0.91},
            {"enneagram_type": 3, "kosha_layer": "manomaya", "resonance_weight": 0.84},
            {"enneagram_type": 8, "kosha_layer": "annamaya", "resonance_weight": 0.62},
            {"enneagram_type": 1, "kosha_layer": "pranamaya", "resonance_weight": 0.55},
        ],
    },
    {
        "node_id": "LORE-ENNEAGMA-0008",
        "bucket_type": "enneagram_biorhythm",
        "source_path": "concept://enneagram/type7_exploration_breath",
        "source_type": "concept",
        "provenance_ref": "canticles:book2:ch08-12",
        "summary": "Type 7 Exploration Breath: the Enthusiast's respiratory pattern is Variable and rapid, with frequent mode-switches that correlate with attention-shifting. The breath is literally 'exploring' -- sampling the respiratory environment without settling into any single rhythm. Under regulation, the 7's exploration shifts from fragmented scanning to directed curiosity: variability becomes coherence with flexibility rather than coherence through rigidity.",
        "text_preview": "Type 7 Exploration Breath: variable rapid breathing with attention-shifting. Regulation directs curiosity into coherent flexibility.",
        "quality_flags": {"concept_type": "biorhythm_pattern", "evidence_level": "theoretical+observational", "enneagram_type": 7},
        "affinities": [
            {"enneagram_type": 7, "kosha_layer": "pranamaya", "resonance_weight": 0.90},
            {"enneagram_type": 7, "kosha_layer": "manomaya", "resonance_weight": 0.83},
            {"enneagram_type": 5, "kosha_layer": "pranamaya", "resonance_weight": 0.55},
            {"enneagram_type": 4, "kosha_layer": "manomaya", "resonance_weight": 0.50},
        ],
    },
]