#!/usr/bin/env python3
"""
Somatic Canticles — Illustrations
Generated by Brandmint pipeline engine.

Provider: fal
"""
import os, sys, subprocess
from dotenv import load_dotenv

ENV_FILE = "~/.claude/.env"
if ENV_FILE:
    load_dotenv(os.path.expanduser(ENV_FILE), override=False)

BRAND_NAME = "Somatic Canticles"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "..", "generated")
os.makedirs(OUT_DIR, exist_ok=True)

# Ensure generated scripts can import local brandmint package adapters.
BRANDMINT_REPO_ROOT = "/private/tmp/brandmint-packaging-20260420"
if BRANDMINT_REPO_ROOT and os.path.isdir(BRANDMINT_REPO_ROOT) and BRANDMINT_REPO_ROOT not in sys.path:
    sys.path.insert(0, BRANDMINT_REPO_ROOT)

# Skill reference images directory (composition references for Nano Banana Pro)
SKILL_REF_DIR = os.path.expanduser("~/.claude/skills/brandmint/references/images")

# =============================================================================
# PROVIDER CONFIGURATION
# =============================================================================
# Supports: fal, openrouter, openai, replicate, inference
# All generation goes through core provider adapters.

PROVIDER = os.environ.get("IMAGE_PROVIDER", "fal").lower()
SUPPORTED_PROVIDERS = {"fal", "openrouter", "openai", "replicate", "inference"}
if PROVIDER not in SUPPORTED_PROVIDERS:
    print(f"WARNING: Unknown provider '{PROVIDER}', defaulting to FAL.")
    PROVIDER = "fal"

INFERENCE_ENDPOINT = "https://api.inference.sh".strip()
if INFERENCE_ENDPOINT:
    os.environ.setdefault("INFERENCE_BASE_URL", INFERENCE_ENDPOINT)
INFERENCE_APP = "".strip()
if INFERENCE_APP:
    os.environ.setdefault("INFERENCE_IMAGE_APP", INFERENCE_APP)

try:
    from brandmint.core.providers import get_provider as _bm_get_provider
except Exception as e:
    print(f"ERROR: Failed to import core provider adapters: {e}")
    sys.exit(1)

try:
    CORE_PROVIDER = _bm_get_provider(PROVIDER)
except Exception as e:
    print(f"ERROR: Provider '{PROVIDER}' is not available: {e}")
    sys.exit(1)

print(f"Using image provider: {PROVIDER.upper()}")

NEGATIVE = """generic new-age aesthetics, chakra clipart, vague energy waves, pulp science fiction,
spaceships, laser guns, stock meditation photography, fantasy creatures, glossy self-help,
cartoon tarot, sterile hospital branding, gradient wellness slop, overblown HDR, cheap metallic effects,
  generic new-age mandalas, chakra clipart, stock meditation photos, pulp-SF ships, vague wellness gradients"""

# Brand logo file (for visual reference injection — empty if no logo configured)
LOGO_PATH = ""

def upload_reference(path):
    """Resolve a local reference path; provider adapters handle upload semantics."""
    if not path or not os.path.exists(path):
        return None
    return os.path.abspath(path)

_logo_url_cache = None
def get_logo_url():
    """Upload brand logo once and cache the URL for reuse."""
    global _logo_url_cache
    if _logo_url_cache:
        return _logo_url_cache
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        print(f"  Uploading brand logo: {os.path.basename(LOGO_PATH)}")
        _logo_url_cache = upload_reference(LOGO_PATH)
        return _logo_url_cache
    return None


# Product reference images (actual product photos for Nano Banana Pro accuracy)
PRODUCT_REF_PATHS = []

_product_ref_url_cache = None
def get_product_ref_urls():
    """Upload product reference images once and cache URLs for reuse."""
    global _product_ref_url_cache
    if _product_ref_url_cache is not None:
        return _product_ref_url_cache
    _product_ref_url_cache = []
    for p in PRODUCT_REF_PATHS:
        if os.path.exists(p):
            print(f"  Uploading product ref: {os.path.basename(p)}")
            uploaded = upload_reference(p)
            if uploaded:
                _product_ref_url_cache.append(uploaded)
    return _product_ref_url_cache


# Reference image mapping: prompt ID -> composition reference filename
REF_IMAGES = {
    "2A": "ref-2A-bento-grid.jpg",
    "2B": "ref-2B-brand-seal.jpg",
    "2C": "ref-2C-logo-emboss.jpg",
    "3A": "ref-3A-capsule-collection.jpg",
    "3B": "ref-3B-hero-product.jpg",
    "3C": "ref-3C-essence-vial.jpg",
    "4A": "ref-4A-catalog-layout.jpg",
    "4B": "ref-4B-flatlay.jpg",
    "5A": "ref-5A-heritage-engraving.jpg",
    "5B": "ref-5B-campaign-grid.jpg",
    "5D": "ref-5D-engine-icons.jpg",
    "7A": "ref-7A-contact-sheet.jpg",
    "8A": "ref-8A-seeker-poster.jpg",
    "9A": "ref-9A-engine-poster.jpg",
    "10A": "ref-7A-contact-sheet.jpg",
    "10B": "ref-7A-contact-sheet.jpg",
    "10C": "ref-7A-contact-sheet.jpg",
}

# Config-driven reference image overrides
REF_OVERRIDES = {}
REF_IMAGES.update(REF_OVERRIDES)


def get_ref_image(pid):
    """Get composition reference image path for a prompt ID."""
    fname = REF_IMAGES.get(pid, "")
    if fname:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            return path
    return None


# Supplementary composition references (dynamically selected from full catalog)
SUPP_REFS = {
    "2A": ['ref-alt-glass-editorial.jpg', 'ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg'],
    "3A": ['ref-alt-product-branding-workflow.jpg', 'ref-alt-passport-covers.jpg', 'ref-alt-varsity-jackets.jpg'],
    "3B": ['ref-alt-passport-covers.jpg', 'ref-alt-product-branding-workflow.jpg', 'ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg'],
    "3C": ['ref-alt-passport-covers.jpg', 'ref-alt-product-branding-workflow.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg'],
    "4A": ['ref-alt-product-branding-workflow.jpg', 'ref-alt-passport-covers.jpg', 'ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg'],
    "4B": ['ref-alt-passport-covers.jpg', 'ref-alt-product-branding-workflow.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg'],
    "5B": ['ref-alt-glass-editorial.jpg', 'ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg'],
    "8A": ['ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini.jpg'],
    "9A": ['ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg', 'ref-tw-097-aleenaamiir-timeline-evolution-dioramas-2.jpg', 'ref-tw-097-aleenaamiir-timeline-evolution-dioramas-3.jpg'],
}

_supp_ref_url_cache = {}
def get_supp_ref_images(pid, limit=3):
    """Get supplementary composition reference URLs for a prompt ID.

    Uploads images on first call, caches for reuse.
    Returns list of uploaded URLs (may be empty).
    """
    if pid in _supp_ref_url_cache:
        return _supp_ref_url_cache[pid]
    urls = []
    for fname in SUPP_REFS.get(pid, [])[:limit]:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            print(f"  Uploading supp ref: {os.path.basename(path)}")
            uploaded = upload_reference(path)
            if uploaded:
                urls.append(uploaded)
    _supp_ref_url_cache[pid] = urls
    return urls


REFERENCE_POLICY = os.environ.get("BRANDMINT_REFERENCE_POLICY", "error").strip().lower()
if REFERENCE_POLICY not in {"error", "warn", "off"}:
    print(f"WARNING: Unknown BRANDMINT_REFERENCE_POLICY '{REFERENCE_POLICY}', defaulting to error.")
    REFERENCE_POLICY = "error"


def _existing_reference_paths(pid):
    """Return local reference files that should anchor a Nano Banana generation."""
    expected = []
    if pid != "2A":
        style_anchor = os.path.join(OUT_DIR, "2A-brand-kit-bento-nanobananapro-v1.png")
        if os.path.exists(style_anchor):
            expected.append(style_anchor)
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        expected.append(LOGO_PATH)
    expected.extend([p for p in PRODUCT_REF_PATHS if os.path.exists(p)])
    ref_path = get_ref_image(pid)
    if ref_path:
        expected.append(ref_path)
    for fname in SUPP_REFS.get(pid, [])[:3]:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            expected.append(path)

    deduped = []
    seen = set()
    for path in expected:
        apath = os.path.abspath(path)
        if apath in seen:
            continue
        seen.add(apath)
        deduped.append(apath)
    return deduped



def enforce_reference_payload(pid, image_urls):
    """Prevent ref-capable Nano Banana steps from silently degrading to text-only."""
    if REFERENCE_POLICY == "off":
        return
    expected = _existing_reference_paths(pid)
    provided = [url for url in (image_urls or []) if url]
    if not expected or provided:
        return

    names = ", ".join(os.path.basename(path) for path in expected[:5])
    message = (
        f"[{pid}] Reference payload missing despite available refs: {names}. "
        "This Nano Banana step would degrade to text-only generation."
    )
    if REFERENCE_POLICY == "warn":
        print(f"WARNING: {message}")
        return
    raise RuntimeError(message)


def _normalize_png_if_needed(filepath):
    """Convert JPEG/WebP/SVG payloads into PNG when output path expects PNG."""
    if not filepath.endswith(".png") or not os.path.exists(filepath):
        return
    with open(filepath, "rb") as f:
        header = f.read(64)
    if header.startswith(b"\x89PNG"):
        return

    try:
        if header[:2] == b"\xff\xd8" or header[:4] == b"RIFF":
            subprocess.run(
                ["sips", "-s", "format", "png", filepath, "--out", filepath],
                check=True,
                capture_output=True,
            )
            return

        head_text = header.decode("utf-8", errors="ignore").lstrip().lower()
        if head_text.startswith("<?xml") or "<svg" in head_text:
            tmp_svg = filepath + ".svg.tmp"
            os.replace(filepath, tmp_svg)
            try:
                subprocess.run(
                    ["rsvg-convert", "-w", "2048", "-h", "2048", "--keep-aspect-ratio", tmp_svg, "-o", filepath],
                    check=True,
                    capture_output=True,
                )
            finally:
                if os.path.exists(tmp_svg):
                    os.remove(tmp_svg)
            return
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"  WARNING: failed to normalize image payload at {filepath}: {e}")


def gen_with_provider(
    prompt,
    model,
    output_path,
    width=1024,
    height=1024,
    image_url=None,
    image_urls=None,
    negative_prompt="",
    **kwargs,
):
    """Generate with core provider adapters only."""
    if CORE_PROVIDER is None:
        return False

    primary_ref = image_url
    if primary_ref is None and isinstance(image_urls, list) and image_urls:
        primary_ref = image_urls[0]

    result = CORE_PROVIDER.generate(
        prompt=prompt,
        model=model,
        output_path=output_path,
        width=width,
        height=height,
        image_url=primary_ref,
        negative_prompt=negative_prompt,
        image_urls=image_urls,
        **kwargs,
    )
    if not (result and result.success):
        err = result.error if result else "unknown adapter error"
        print(f"  ERROR: generation failed for {model} via {PROVIDER}: {err}")
        return False

    _normalize_png_if_needed(output_path)
    if os.path.exists(output_path):
        size_kb = os.path.getsize(output_path) / 1024
        print(f"  Saved: {os.path.basename(output_path)} ({size_kb:.0f} KB)")
    return True


def gen_recraft(pid, slug, prompt, style, colors, size, seeds=(42, 137)):
    """Generate with Recraft V3 via unified core provider adapter path."""
    size_dims = {"square": (1024, 1024), "landscape_16_9": (1792, 1024), 
                 "portrait_9_16": (1024, 1792), "1024x1024": (1024, 1024)}
    w, h = size_dims.get(size, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-recraft-{variant}.png")
        print(f"\n  [{pid}] Recraft V3 ({style}) seed={seed} (provider: {PROVIDER})...")
        gen_with_provider(
            prompt,
            "recraft-v3",
            out_path,
            w,
            h,
            negative_prompt="",
            seed=seed,
            image_size=size,
            style=style,
            colors=colors,
        )


def gen_nano_banana(pid, slug, prompt, aspect, image_urls, seeds=(42, 137)):
    """Generate with Nano Banana Pro via unified core provider adapter path."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"
    enforce_reference_payload(pid, image_urls)
    
    # Parse aspect ratio to get dimensions
    aspect_dims = {"16:9": (1792, 1024), "9:16": (1024, 1792), "1:1": (1024, 1024), 
                   "3:4": (896, 1152), "4:3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-nanobananapro-{variant}.png")
        print(f"\n  [{pid}] Nano Banana Pro seed={seed} (provider: {PROVIDER})...")
        gen_with_provider(
            full_prompt,
            "nano-banana-pro",
            out_path,
            w,
            h,
            image_urls=image_urls,
            negative_prompt="",
            seed=seed,
            aspect_ratio=aspect,
            resolution="2K",
            output_format="png",
            num_images=1,
        )


def gen_flux_pro(pid, slug, prompt, aspect, seeds=(42, 137)):
    """Generate with Flux 2 Pro via unified core provider adapter path."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"
    
    # Parse aspect to dimensions
    aspect_dims = {"landscape_16_9": (1792, 1024), "portrait_9_16": (1024, 1792), 
                   "square": (1024, 1024), "portrait_3_4": (896, 1152), "landscape_4_3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-flux2pro-{variant}.png")
        print(f"\n  [{pid}] Flux 2 Pro seed={seed} (provider: {PROVIDER})...")
        gen_with_provider(
            full_prompt,
            "flux-2-pro",
            out_path,
            w,
            h,
            negative_prompt="",
            seed=seed,
            image_size=aspect,
            num_images=1,
        )



PROMPT_BOOK_COVER_1_ANAMNESIS_ENGINE = """Premium literary book cover for Somatic Canticles: Anamnesis Engine.
Narrative focus: diagnosis, neural systems, and memory architecture. Design a front-cover artwork system suitable for a hardcover edition with sacred anatomy, Tarot-biological geometry, and hard-SF editorial restraint.
The trilogy visual language must stay consistent with Deep Neural Indigo structure, Soma Gold foil logic, and Severance Violet transformation cues.
Feels adjacent to Tor Books literary SF design and Alex Grey sacred anatomy without imitating either directly.
No title text, no author text, no fake blurbs, no pulp spaceship imagery.
"""

PROMPT_BOOK_COVER_2_MYOCARDIAL_CHORUS = """Premium literary book cover for Somatic Canticles: The Myocardial Chorus.
Narrative focus: cardiac intelligence, vagal systems, and the body becoming choir. Design a front-cover artwork system suitable for a hardcover edition with sacred anatomy, Tarot-biological geometry, and hard-SF editorial restraint.
The trilogy visual language must stay consistent with Deep Neural Indigo structure, Soma Gold foil logic, and Severance Violet transformation cues.
Feels adjacent to Tor Books literary SF design and Alex Grey sacred anatomy without imitating either directly.
No title text, no author text, no fake blurbs, no pulp spaceship imagery.
"""

PROMPT_BOOK_COVER_3_THE_RIPENING = """Premium literary book cover for Somatic Canticles: The Ripening.
Narrative focus: systemic coherence, liberation, and the Aletheia versus Lethe choice. Design a front-cover artwork system suitable for a hardcover edition with sacred anatomy, Tarot-biological geometry, and hard-SF editorial restraint.
The trilogy visual language must stay consistent with Deep Neural Indigo structure, Soma Gold foil logic, and Severance Violet transformation cues.
Feels adjacent to Tor Books literary SF design and Alex Grey sacred anatomy without imitating either directly.
No title text, no author text, no fake blurbs, no pulp spaceship imagery.
"""

PROMPT_00_FOOL_STEM_CELL = """Somatic Canticles Major Arcana card 00: The Fool.
Biological event: stem cell potential. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_01_MAGICIAN_NEUROPLASTICITY = """Somatic Canticles Major Arcana card 01: The Magician.
Biological event: neuroplasticity. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_02_HIGH_PRIESTESS_PINEAL = """Somatic Canticles Major Arcana card 02: The High Priestess.
Biological event: pineal awakening. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_03_EMPRESS_OXYTOCIN = """Somatic Canticles Major Arcana card 03: The Empress.
Biological event: oxytocin bonding. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_04_EMPEROR_PREFRONTAL = """Somatic Canticles Major Arcana card 04: The Emperor.
Biological event: prefrontal regulation. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_05_HIEROPHANT_MIRROR_NEURONS = """Somatic Canticles Major Arcana card 05: The Hierophant.
Biological event: mirror neuron entrainment. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_06_LOVERS_DOPAMINE = """Somatic Canticles Major Arcana card 06: The Lovers.
Biological event: dopamine pairing. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_07_CHARIOT_CARDIAC_COHERENCE = """Somatic Canticles Major Arcana card 07: The Chariot.
Biological event: cardiac coherence. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_08_STRENGTH_IMMUNE = """Somatic Canticles Major Arcana card 08: Strength.
Biological event: immune intelligence. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_09_HERMIT_AUTOPHAGY = """Somatic Canticles Major Arcana card 09: The Hermit.
Biological event: autophagy. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_10_WHEEL_CIRCADIAN = """Somatic Canticles Major Arcana card 10: Wheel of Fortune.
Biological event: circadian timing. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_11_JUSTICE_HORMONAL = """Somatic Canticles Major Arcana card 11: Justice.
Biological event: hormonal balance. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_12_HANGEDMAN_PARASYMPATHETIC = """Somatic Canticles Major Arcana card 12: The Hanged Man.
Biological event: parasympathetic surrender. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_13_DEATH_APOPTOSIS = """Somatic Canticles Major Arcana card 13: Death.
Biological event: apoptosis. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_14_TEMPERANCE_METABOLIC = """Somatic Canticles Major Arcana card 14: Temperance.
Biological event: metabolic equilibrium. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_15_DEVIL_ADDICTION = """Somatic Canticles Major Arcana card 15: The Devil.
Biological event: addiction loops. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_16_TOWER_SEVERANCE = """Somatic Canticles Major Arcana card 16: The Tower.
Biological event: the severance event. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_17_STAR_NEUROGENESIS = """Somatic Canticles Major Arcana card 17: The Star.
Biological event: neurogenesis. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_18_MOON_REM_SLEEP = """Somatic Canticles Major Arcana card 18: The Moon.
Biological event: REM sleep. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_19_SUN_MITOCHONDRIA = """Somatic Canticles Major Arcana card 19: The Sun.
Biological event: mitochondrial radiance. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_20_JUDGEMENT_EPIGENETICS = """Somatic Canticles Major Arcana card 20: Judgement.
Biological event: epigenetic awakening. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_21_WORLD_HOMEOSTASIS = """Somatic Canticles Major Arcana card 21: The World.
Biological event: homeostasis. Sacred anatomy Tarot panel in a vertical card frame.
Style: Sacred anatomy illustration blending medical precision, Tarot structure, and cosmic linework. References: Alex Grey sacred anatomy, medical illustration, Rider-Waite-Smith Major Arcana, Tor literary SF covers.
Clinical precision fused with mythic symbolism. Deep Neural Indigo dominates, Soma Gold as a surgical highlight, Severance Violet used sparingly for transformation cues.
Mood keywords: clinical-mysticism, rigorous-sacred, hard-sf, sacred-anatomy, tarot-biological, luminous, indigo, gold, cardiac, transformational. Render as a premium literary sacred-anatomy artifact, not fantasy slop.
No text, no card labels, no generic new-age symbols, no clipart.
"""

PROMPT_ANATOMY_CARDIAC_COHERENCE = """Somatic Canticles anatomy plate: Cardiac Coherence.
Subject focus: cardiac coherence field geometry. Sacred anatomy illustration with medical-illustration fidelity and luminous cosmic linework.
Materials and motifs: deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. Environment: Deep-indigo studio environments, atlas pages, luminous biology, and restrained sacred geometry.
Clinical Mysticism aesthetic, atlas-page composition, gold technical annotations implied but not written.
Premium editorial restraint, deep-indigo field, neuronal-white anatomy surfaces, soma-gold signal accents.
No stock wellness imagery, no pulp-SF props, no decorative mandalas, no text.
"""

PROMPT_ANATOMY_HEART_BRAIN_AXIS = """Somatic Canticles anatomy plate: Heart Brain Axis.
Subject focus: heart-brain axis circuitry. Sacred anatomy illustration with medical-illustration fidelity and luminous cosmic linework.
Materials and motifs: deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. Environment: Deep-indigo studio environments, atlas pages, luminous biology, and restrained sacred geometry.
Clinical Mysticism aesthetic, atlas-page composition, gold technical annotations implied but not written.
Premium editorial restraint, deep-indigo field, neuronal-white anatomy surfaces, soma-gold signal accents.
No stock wellness imagery, no pulp-SF props, no decorative mandalas, no text.
"""

PROMPT_ANATOMY_KHALOREE_FIELD_ARCHITECTURE = """Somatic Canticles anatomy plate: Khaloree Field Architecture.
Subject focus: Khaloree field architecture. Sacred anatomy illustration with medical-illustration fidelity and luminous cosmic linework.
Materials and motifs: deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. Environment: Deep-indigo studio environments, atlas pages, luminous biology, and restrained sacred geometry.
Clinical Mysticism aesthetic, atlas-page composition, gold technical annotations implied but not written.
Premium editorial restraint, deep-indigo field, neuronal-white anatomy surfaces, soma-gold signal accents.
No stock wellness imagery, no pulp-SF props, no decorative mandalas, no text.
"""

PROMPT_ANATOMY_NEURAL_DENDRITES = """Somatic Canticles anatomy plate: Neural Dendrites.
Subject focus: luminous neural dendrite arbor. Sacred anatomy illustration with medical-illustration fidelity and luminous cosmic linework.
Materials and motifs: deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. Environment: Deep-indigo studio environments, atlas pages, luminous biology, and restrained sacred geometry.
Clinical Mysticism aesthetic, atlas-page composition, gold technical annotations implied but not written.
Premium editorial restraint, deep-indigo field, neuronal-white anatomy surfaces, soma-gold signal accents.
No stock wellness imagery, no pulp-SF props, no decorative mandalas, no text.
"""

PROMPT_ANATOMY_SEVERANCE_PATHWAYS = """Somatic Canticles anatomy plate: Severance Pathways.
Subject focus: severance pathways through the nervous system. Sacred anatomy illustration with medical-illustration fidelity and luminous cosmic linework.
Materials and motifs: deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. Environment: Deep-indigo studio environments, atlas pages, luminous biology, and restrained sacred geometry.
Clinical Mysticism aesthetic, atlas-page composition, gold technical annotations implied but not written.
Premium editorial restraint, deep-indigo field, neuronal-white anatomy surfaces, soma-gold signal accents.
No stock wellness imagery, no pulp-SF props, no decorative mandalas, no text.
"""

PROMPT_ANATOMY_SOMATIC_MAPPING = """Somatic Canticles anatomy plate: Somatic Mapping.
Subject focus: somatic mapping overlays. Sacred anatomy illustration with medical-illustration fidelity and luminous cosmic linework.
Materials and motifs: deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. Environment: Deep-indigo studio environments, atlas pages, luminous biology, and restrained sacred geometry.
Clinical Mysticism aesthetic, atlas-page composition, gold technical annotations implied but not written.
Premium editorial restraint, deep-indigo field, neuronal-white anatomy surfaces, soma-gold signal accents.
No stock wellness imagery, no pulp-SF props, no decorative mandalas, no text.
"""

PROMPT_ANATOMY_TRIANGULATION_ENGINE = """Somatic Canticles anatomy plate: Triangulation Engine.
Subject focus: triangulation engine architecture. Sacred anatomy illustration with medical-illustration fidelity and luminous cosmic linework.
Materials and motifs: deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. Environment: Deep-indigo studio environments, atlas pages, luminous biology, and restrained sacred geometry.
Clinical Mysticism aesthetic, atlas-page composition, gold technical annotations implied but not written.
Premium editorial restraint, deep-indigo field, neuronal-white anatomy surfaces, soma-gold signal accents.
No stock wellness imagery, no pulp-SF props, no decorative mandalas, no text.
"""

PROMPT_ANATOMY_VAGAL_NERVE = """Somatic Canticles anatomy plate: Vagal Nerve.
Subject focus: vagal nerve pathway. Sacred anatomy illustration with medical-illustration fidelity and luminous cosmic linework.
Materials and motifs: deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. Environment: Deep-indigo studio environments, atlas pages, luminous biology, and restrained sacred geometry.
Clinical Mysticism aesthetic, atlas-page composition, gold technical annotations implied but not written.
Premium editorial restraint, deep-indigo field, neuronal-white anatomy surfaces, soma-gold signal accents.
No stock wellness imagery, no pulp-SF props, no decorative mandalas, no text.
"""


STYLE_ANCHOR = os.path.join(OUT_DIR, "2A-brand-kit-bento-nanobananapro-v1.png")


def main():
    print("=" * 60)
    print(f"{BRAND_NAME} -- Illustrations")
    print("=" * 60)

    anchor_urls = []
    if os.path.exists(STYLE_ANCHOR):
        anchor_url = upload_reference(STYLE_ANCHOR)
        if anchor_url:
            anchor_urls = [anchor_url]
    logo_url = get_logo_url()
    if logo_url:
        anchor_urls.append(logo_url)

    # Verify Recraft prompt lengths
    for pid, p in {}.items():
        if pid not in ['ANATOMY-CARDIAC-COHERENCE', 'ANATOMY-HEART-BRAIN-AXIS', 'ANATOMY-KHALOREE-FIELD-ARCHITECTURE', 'ANATOMY-NEURAL-DENDRITES', 'ANATOMY-SEVERANCE-PATHWAYS', 'ANATOMY-SOMATIC-MAPPING', 'ANATOMY-TRIANGULATION-ENGINE', 'ANATOMY-VAGAL-NERVE', 'ARCANA-00-FOOL', 'ARCANA-01-MAGICIAN', 'ARCANA-02-HIGH-PRIESTESS', 'ARCANA-03-EMPRESS', 'ARCANA-04-EMPEROR', 'ARCANA-05-HIEROPHANT', 'ARCANA-06-LOVERS', 'ARCANA-07-CHARIOT', 'ARCANA-08-STRENGTH', 'ARCANA-09-HERMIT', 'ARCANA-10-WHEEL', 'ARCANA-11-JUSTICE', 'ARCANA-12-HANGED-MAN', 'ARCANA-13-DEATH', 'ARCANA-14-TEMPERANCE', 'ARCANA-15-DEVIL', 'ARCANA-16-TOWER', 'ARCANA-17-STAR', 'ARCANA-18-MOON', 'ARCANA-19-SUN', 'ARCANA-20-JUDGEMENT', 'ARCANA-21-WORLD', 'COVER-ANAMNESIS-ENGINE', 'COVER-MYOCARDIAL-CHORUS', 'COVER-THE-RIPENING']:
            continue
        count = len(p)
        status = "OK" if count < 1000 else "OVER LIMIT"
        print(f"  {pid}: {count} chars [{status}]")
        if count >= 1000:
            print("ERROR: Prompt exceeds 1000 char Recraft V3 limit before submission.")
            sys.exit(1)



    print("\n--- COVER-ANAMNESIS-ENGINE: Book Cover - Anamnesis Engine (Nano Banana Pro) ---")
    gen_nano_banana("COVER-ANAMNESIS-ENGINE", "book-cover-1-anamnesis-engine", PROMPT_BOOK_COVER_1_ANAMNESIS_ENGINE, "portrait_3_4", anchor_urls)

    print("\n--- COVER-MYOCARDIAL-CHORUS: Book Cover - The Myocardial Chorus (Nano Banana Pro) ---")
    gen_nano_banana("COVER-MYOCARDIAL-CHORUS", "book-cover-2-myocardial-chorus", PROMPT_BOOK_COVER_2_MYOCARDIAL_CHORUS, "portrait_3_4", anchor_urls)

    print("\n--- COVER-THE-RIPENING: Book Cover - The Ripening (Nano Banana Pro) ---")
    gen_nano_banana("COVER-THE-RIPENING", "book-cover-3-the-ripening", PROMPT_BOOK_COVER_3_THE_RIPENING, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-00-FOOL: Arcana 00 - The Fool / Stem Cell (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-00-FOOL", "00-fool-stem-cell", PROMPT_00_FOOL_STEM_CELL, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-01-MAGICIAN: Arcana 01 - The Magician / Neuroplasticity (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-01-MAGICIAN", "01-magician-neuroplasticity", PROMPT_01_MAGICIAN_NEUROPLASTICITY, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-02-HIGH-PRIESTESS: Arcana 02 - The High Priestess / Pineal (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-02-HIGH-PRIESTESS", "02-high-priestess-pineal", PROMPT_02_HIGH_PRIESTESS_PINEAL, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-03-EMPRESS: Arcana 03 - The Empress / Oxytocin (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-03-EMPRESS", "03-empress-oxytocin", PROMPT_03_EMPRESS_OXYTOCIN, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-04-EMPEROR: Arcana 04 - The Emperor / Prefrontal Cortex (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-04-EMPEROR", "04-emperor-prefrontal", PROMPT_04_EMPEROR_PREFRONTAL, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-05-HIEROPHANT: Arcana 05 - The Hierophant / Mirror Neurons (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-05-HIEROPHANT", "05-hierophant-mirror-neurons", PROMPT_05_HIEROPHANT_MIRROR_NEURONS, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-06-LOVERS: Arcana 06 - The Lovers / Dopamine (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-06-LOVERS", "06-lovers-dopamine", PROMPT_06_LOVERS_DOPAMINE, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-07-CHARIOT: Arcana 07 - The Chariot / Cardiac Coherence (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-07-CHARIOT", "07-chariot-cardiac-coherence", PROMPT_07_CHARIOT_CARDIAC_COHERENCE, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-08-STRENGTH: Arcana 08 - Strength / Immune Intelligence (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-08-STRENGTH", "08-strength-immune", PROMPT_08_STRENGTH_IMMUNE, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-09-HERMIT: Arcana 09 - The Hermit / Autophagy (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-09-HERMIT", "09-hermit-autophagy", PROMPT_09_HERMIT_AUTOPHAGY, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-10-WHEEL: Arcana 10 - Wheel of Fortune / Circadian (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-10-WHEEL", "10-wheel-circadian", PROMPT_10_WHEEL_CIRCADIAN, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-11-JUSTICE: Arcana 11 - Justice / Hormonal Balance (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-11-JUSTICE", "11-justice-hormonal", PROMPT_11_JUSTICE_HORMONAL, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-12-HANGED-MAN: Arcana 12 - The Hanged Man / Parasympathetic (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-12-HANGED-MAN", "12-hangedman-parasympathetic", PROMPT_12_HANGEDMAN_PARASYMPATHETIC, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-13-DEATH: Arcana 13 - Death / Apoptosis (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-13-DEATH", "13-death-apoptosis", PROMPT_13_DEATH_APOPTOSIS, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-14-TEMPERANCE: Arcana 14 - Temperance / Metabolic Balance (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-14-TEMPERANCE", "14-temperance-metabolic", PROMPT_14_TEMPERANCE_METABOLIC, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-15-DEVIL: Arcana 15 - The Devil / Addiction (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-15-DEVIL", "15-devil-addiction", PROMPT_15_DEVIL_ADDICTION, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-16-TOWER: Arcana 16 - The Tower / Severance (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-16-TOWER", "16-tower-severance", PROMPT_16_TOWER_SEVERANCE, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-17-STAR: Arcana 17 - The Star / Neurogenesis (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-17-STAR", "17-star-neurogenesis", PROMPT_17_STAR_NEUROGENESIS, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-18-MOON: Arcana 18 - The Moon / REM Sleep (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-18-MOON", "18-moon-rem-sleep", PROMPT_18_MOON_REM_SLEEP, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-19-SUN: Arcana 19 - The Sun / Mitochondria (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-19-SUN", "19-sun-mitochondria", PROMPT_19_SUN_MITOCHONDRIA, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-20-JUDGEMENT: Arcana 20 - Judgement / Epigenetics (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-20-JUDGEMENT", "20-judgement-epigenetics", PROMPT_20_JUDGEMENT_EPIGENETICS, "portrait_3_4", anchor_urls)

    print("\n--- ARCANA-21-WORLD: Arcana 21 - The World / Homeostasis (Nano Banana Pro) ---")
    gen_nano_banana("ARCANA-21-WORLD", "21-world-homeostasis", PROMPT_21_WORLD_HOMEOSTASIS, "portrait_3_4", anchor_urls)

    print("\n--- ANATOMY-CARDIAC-COHERENCE: Anatomy Plate - Cardiac Coherence (Nano Banana Pro) ---")
    gen_nano_banana("ANATOMY-CARDIAC-COHERENCE", "anatomy-cardiac-coherence", PROMPT_ANATOMY_CARDIAC_COHERENCE, "portrait_3_4", anchor_urls)

    print("\n--- ANATOMY-HEART-BRAIN-AXIS: Anatomy Plate - Heart Brain Axis (Nano Banana Pro) ---")
    gen_nano_banana("ANATOMY-HEART-BRAIN-AXIS", "anatomy-heart-brain-axis", PROMPT_ANATOMY_HEART_BRAIN_AXIS, "portrait_3_4", anchor_urls)

    print("\n--- ANATOMY-KHALOREE-FIELD-ARCHITECTURE: Anatomy Plate - Khaloree Field Architecture (Nano Banana Pro) ---")
    gen_nano_banana("ANATOMY-KHALOREE-FIELD-ARCHITECTURE", "anatomy-khaloree-field-architecture", PROMPT_ANATOMY_KHALOREE_FIELD_ARCHITECTURE, "portrait_3_4", anchor_urls)

    print("\n--- ANATOMY-NEURAL-DENDRITES: Anatomy Plate - Neural Dendrites (Nano Banana Pro) ---")
    gen_nano_banana("ANATOMY-NEURAL-DENDRITES", "anatomy-neural-dendrites", PROMPT_ANATOMY_NEURAL_DENDRITES, "portrait_3_4", anchor_urls)

    print("\n--- ANATOMY-SEVERANCE-PATHWAYS: Anatomy Plate - Severance Pathways (Nano Banana Pro) ---")
    gen_nano_banana("ANATOMY-SEVERANCE-PATHWAYS", "anatomy-severance-pathways", PROMPT_ANATOMY_SEVERANCE_PATHWAYS, "portrait_3_4", anchor_urls)

    print("\n--- ANATOMY-SOMATIC-MAPPING: Anatomy Plate - Somatic Mapping (Nano Banana Pro) ---")
    gen_nano_banana("ANATOMY-SOMATIC-MAPPING", "anatomy-somatic-mapping", PROMPT_ANATOMY_SOMATIC_MAPPING, "portrait_3_4", anchor_urls)

    print("\n--- ANATOMY-TRIANGULATION-ENGINE: Anatomy Plate - Triangulation Engine (Nano Banana Pro) ---")
    gen_nano_banana("ANATOMY-TRIANGULATION-ENGINE", "anatomy-triangulation-engine", PROMPT_ANATOMY_TRIANGULATION_ENGINE, "portrait_3_4", anchor_urls)

    print("\n--- ANATOMY-VAGAL-NERVE: Anatomy Plate - Vagal Nerve (Nano Banana Pro) ---")
    gen_nano_banana("ANATOMY-VAGAL-NERVE", "anatomy-vagal-nerve", PROMPT_ANATOMY_VAGAL_NERVE, "portrait_3_4", anchor_urls)

    print("\n" + "=" * 60)
    print("  ILLUSTRATIONS COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
