#!/usr/bin/env python3
"""
Somatic Canticles — Product Photography (4A + 4B)
Generated by Brandmint pipeline engine.

Provider: fal
"""
import os, sys, subprocess
from dotenv import load_dotenv

ENV_FILE = "~/.claude/.env"
if ENV_FILE:
    load_dotenv(os.path.expanduser(ENV_FILE), override=False)

BRAND_NAME = "Somatic Canticles"
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(SCRIPT_DIR, "..", "generated")
os.makedirs(OUT_DIR, exist_ok=True)

# Ensure generated scripts can import local brandmint package adapters.
BRANDMINT_REPO_ROOT = "/Volumes/madara/2026/twc-vault/01-Projects/brandmint"
if BRANDMINT_REPO_ROOT and os.path.isdir(BRANDMINT_REPO_ROOT) and BRANDMINT_REPO_ROOT not in sys.path:
    sys.path.insert(0, BRANDMINT_REPO_ROOT)

# Skill reference images directory (composition references for Nano Banana Pro)
SKILL_REF_DIR = os.path.expanduser("~/.claude/skills/brandmint/references/images")

# =============================================================================
# PROVIDER CONFIGURATION
# =============================================================================
# Supports: fal, openrouter, openai, replicate, inference
# All generation goes through core provider adapters.

PROVIDER = os.environ.get("IMAGE_PROVIDER", "fal").lower()
SUPPORTED_PROVIDERS = {"fal", "openrouter", "openai", "replicate", "inference"}
if PROVIDER not in SUPPORTED_PROVIDERS:
    print(f"WARNING: Unknown provider '{PROVIDER}', defaulting to FAL.")
    PROVIDER = "fal"

INFERENCE_ENDPOINT = "https://api.inference.sh".strip()
if INFERENCE_ENDPOINT:
    os.environ.setdefault("INFERENCE_BASE_URL", INFERENCE_ENDPOINT)
INFERENCE_APP = "".strip()
if INFERENCE_APP:
    os.environ.setdefault("INFERENCE_IMAGE_APP", INFERENCE_APP)

try:
    from brandmint.core.providers import get_provider as _bm_get_provider
except Exception as e:
    print(f"ERROR: Failed to import core provider adapters: {e}")
    sys.exit(1)

try:
    CORE_PROVIDER = _bm_get_provider(PROVIDER)
except Exception as e:
    print(f"ERROR: Provider '{PROVIDER}' is not available: {e}")
    sys.exit(1)

print(f"Using image provider: {PROVIDER.upper()}")

NEGATIVE = """generic new-age aesthetics, chakra clipart, vague energy waves, pulp science fiction,
spaceships, laser guns, stock meditation photography, fantasy creatures, glossy self-help,
cartoon tarot, sterile hospital branding, gradient wellness slop, overblown HDR, cheap metallic effects,
  generic new-age mandalas, chakra clipart, stock meditation photos, pulp-SF ships, vague wellness gradients"""

# Brand logo file (for visual reference injection — empty if no logo configured)
LOGO_PATH = ""

def upload_reference(path):
    """Resolve a local reference path; provider adapters handle upload semantics."""
    if not path or not os.path.exists(path):
        return None
    return os.path.abspath(path)

_logo_url_cache = None
def get_logo_url():
    """Upload brand logo once and cache the URL for reuse."""
    global _logo_url_cache
    if _logo_url_cache:
        return _logo_url_cache
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        print(f"  Uploading brand logo: {os.path.basename(LOGO_PATH)}")
        _logo_url_cache = upload_reference(LOGO_PATH)
        return _logo_url_cache
    return None


# Product reference images (actual product photos for Nano Banana Pro accuracy)
PRODUCT_REF_PATHS = []

_product_ref_url_cache = None
def get_product_ref_urls():
    """Upload product reference images once and cache URLs for reuse."""
    global _product_ref_url_cache
    if _product_ref_url_cache is not None:
        return _product_ref_url_cache
    _product_ref_url_cache = []
    for p in PRODUCT_REF_PATHS:
        if os.path.exists(p):
            print(f"  Uploading product ref: {os.path.basename(p)}")
            uploaded = upload_reference(p)
            if uploaded:
                _product_ref_url_cache.append(uploaded)
    return _product_ref_url_cache


# Reference image mapping: prompt ID -> composition reference filename
REF_IMAGES = {
    "2A": "ref-2A-bento-grid.jpg",
    "2B": "ref-2B-brand-seal.jpg",
    "2C": "ref-2C-logo-emboss.jpg",
    "3A": "ref-3A-capsule-collection.jpg",
    "3B": "ref-3B-hero-product.jpg",
    "3C": "ref-3C-essence-vial.jpg",
    "4A": "ref-4A-catalog-layout.jpg",
    "4B": "ref-4B-flatlay.jpg",
    "5A": "ref-5A-heritage-engraving.jpg",
    "5B": "ref-5B-campaign-grid.jpg",
    "5D": "ref-5D-engine-icons.jpg",
    "7A": "ref-7A-contact-sheet.jpg",
    "8A": "ref-8A-seeker-poster.jpg",
    "9A": "ref-9A-engine-poster.jpg",
    "10A": "ref-7A-contact-sheet.jpg",
    "10B": "ref-7A-contact-sheet.jpg",
    "10C": "ref-7A-contact-sheet.jpg",
}

# Config-driven reference image overrides
REF_OVERRIDES = {}
REF_IMAGES.update(REF_OVERRIDES)


def get_ref_image(pid):
    """Get composition reference image path for a prompt ID."""
    fname = REF_IMAGES.get(pid, "")
    if fname:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            return path
    return None


# Supplementary composition references (dynamically selected from full catalog)
SUPP_REFS = {
    "2A": ['ref-alt-glass-editorial.jpg', 'ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg'],
    "3A": ['ref-alt-product-branding-workflow.jpg', 'ref-alt-passport-covers.jpg', 'ref-alt-varsity-jackets.jpg'],
    "3B": ['ref-alt-passport-covers.jpg', 'ref-alt-product-branding-workflow.jpg', 'ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg'],
    "3C": ['ref-alt-passport-covers.jpg', 'ref-alt-product-branding-workflow.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg'],
    "4A": ['ref-alt-product-branding-workflow.jpg', 'ref-alt-passport-covers.jpg', 'ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg'],
    "4B": ['ref-alt-passport-covers.jpg', 'ref-alt-product-branding-workflow.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg'],
    "5B": ['ref-alt-glass-editorial.jpg', 'ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg'],
    "8A": ['ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini-2.jpg', 'ref-tw-051-j_smeaton99-google-nano-banana-pro-gemini.jpg'],
    "9A": ['ref-tw-010-Strength04_X-recipe-powered-google-nano.jpg', 'ref-tw-097-aleenaamiir-timeline-evolution-dioramas-2.jpg', 'ref-tw-097-aleenaamiir-timeline-evolution-dioramas-3.jpg'],
}

_supp_ref_url_cache = {}
def get_supp_ref_images(pid, limit=3):
    """Get supplementary composition reference URLs for a prompt ID.

    Uploads images on first call, caches for reuse.
    Returns list of uploaded URLs (may be empty).
    """
    if pid in _supp_ref_url_cache:
        return _supp_ref_url_cache[pid]
    urls = []
    for fname in SUPP_REFS.get(pid, [])[:limit]:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            print(f"  Uploading supp ref: {os.path.basename(path)}")
            uploaded = upload_reference(path)
            if uploaded:
                urls.append(uploaded)
    _supp_ref_url_cache[pid] = urls
    return urls


REFERENCE_POLICY = os.environ.get("BRANDMINT_REFERENCE_POLICY", "error").strip().lower()
if REFERENCE_POLICY not in {"error", "warn", "off"}:
    print(f"WARNING: Unknown BRANDMINT_REFERENCE_POLICY '{REFERENCE_POLICY}', defaulting to error.")
    REFERENCE_POLICY = "error"


def _existing_reference_paths(pid):
    """Return local reference files that should anchor a Nano Banana generation."""
    expected = []
    if pid != "2A":
        style_anchor = os.path.join(OUT_DIR, "2A-brand-kit-bento-nanobananapro-v1.png")
        if os.path.exists(style_anchor):
            expected.append(style_anchor)
    if LOGO_PATH and os.path.exists(LOGO_PATH):
        expected.append(LOGO_PATH)
    expected.extend([p for p in PRODUCT_REF_PATHS if os.path.exists(p)])
    ref_path = get_ref_image(pid)
    if ref_path:
        expected.append(ref_path)
    for fname in SUPP_REFS.get(pid, [])[:3]:
        path = os.path.join(SKILL_REF_DIR, fname)
        if os.path.exists(path):
            expected.append(path)

    deduped = []
    seen = set()
    for path in expected:
        apath = os.path.abspath(path)
        if apath in seen:
            continue
        seen.add(apath)
        deduped.append(apath)
    return deduped



def enforce_reference_payload(pid, image_urls):
    """Prevent ref-capable Nano Banana steps from silently degrading to text-only."""
    if REFERENCE_POLICY == "off":
        return
    expected = _existing_reference_paths(pid)
    provided = [url for url in (image_urls or []) if url]
    if not expected or provided:
        return

    names = ", ".join(os.path.basename(path) for path in expected[:5])
    message = (
        f"[{pid}] Reference payload missing despite available refs: {names}. "
        "This Nano Banana step would degrade to text-only generation."
    )
    if REFERENCE_POLICY == "warn":
        print(f"WARNING: {message}")
        return
    raise RuntimeError(message)


def _normalize_png_if_needed(filepath):
    """Convert JPEG/WebP/SVG payloads into PNG when output path expects PNG."""
    if not filepath.endswith(".png") or not os.path.exists(filepath):
        return
    with open(filepath, "rb") as f:
        header = f.read(64)
    if header.startswith(b"\x89PNG"):
        return

    try:
        if header[:2] == b"\xff\xd8" or header[:4] == b"RIFF":
            subprocess.run(
                ["sips", "-s", "format", "png", filepath, "--out", filepath],
                check=True,
                capture_output=True,
            )
            return

        head_text = header.decode("utf-8", errors="ignore").lstrip().lower()
        if head_text.startswith("<?xml") or "<svg" in head_text:
            tmp_svg = filepath + ".svg.tmp"
            os.replace(filepath, tmp_svg)
            try:
                subprocess.run(
                    ["rsvg-convert", "-w", "2048", "-h", "2048", "--keep-aspect-ratio", tmp_svg, "-o", filepath],
                    check=True,
                    capture_output=True,
                )
            finally:
                if os.path.exists(tmp_svg):
                    os.remove(tmp_svg)
            return
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        print(f"  WARNING: failed to normalize image payload at {filepath}: {e}")


def gen_with_provider(
    prompt,
    model,
    output_path,
    width=1024,
    height=1024,
    image_url=None,
    image_urls=None,
    negative_prompt="",
    **kwargs,
):
    """Generate with core provider adapters only."""
    if CORE_PROVIDER is None:
        return False

    primary_ref = image_url
    if primary_ref is None and isinstance(image_urls, list) and image_urls:
        primary_ref = image_urls[0]

    result = CORE_PROVIDER.generate(
        prompt=prompt,
        model=model,
        output_path=output_path,
        width=width,
        height=height,
        image_url=primary_ref,
        negative_prompt=negative_prompt,
        image_urls=image_urls,
        **kwargs,
    )
    if not (result and result.success):
        err = result.error if result else "unknown adapter error"
        print(f"  ERROR: generation failed for {model} via {PROVIDER}: {err}")
        return False

    _normalize_png_if_needed(output_path)
    if os.path.exists(output_path):
        size_kb = os.path.getsize(output_path) / 1024
        print(f"  Saved: {os.path.basename(output_path)} ({size_kb:.0f} KB)")
    return True


def gen_nano_banana(pid, slug, prompt, aspect, image_urls, seeds=(42, 137)):
    """Generate with Nano Banana Pro via unified core provider adapter path."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"
    enforce_reference_payload(pid, image_urls)
    
    # Parse aspect ratio to get dimensions
    aspect_dims = {"16:9": (1792, 1024), "9:16": (1024, 1792), "1:1": (1024, 1024), 
                   "3:4": (896, 1152), "4:3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-nanobananapro-{variant}.png")
        print(f"\n  [{pid}] Nano Banana Pro seed={seed} (provider: {PROVIDER})...")
        gen_with_provider(
            full_prompt,
            "nano-banana-pro",
            out_path,
            w,
            h,
            image_urls=image_urls,
            negative_prompt="",
            seed=seed,
            aspect_ratio=aspect,
            resolution="2K",
            output_format="png",
            num_images=1,
        )


def gen_flux_pro(pid, slug, prompt, aspect, seeds=(42, 137)):
    """Generate with Flux 2 Pro via unified core provider adapter path."""
    full_prompt = f"{prompt}\n\nAvoid: {NEGATIVE}"
    
    # Parse aspect to dimensions
    aspect_dims = {"landscape_16_9": (1792, 1024), "portrait_9_16": (1024, 1792), 
                   "square": (1024, 1024), "portrait_3_4": (896, 1152), "landscape_4_3": (1152, 896)}
    w, h = aspect_dims.get(aspect, (1024, 1024))
    
    for seed in seeds:
        variant = "v1" if seed == 42 else f"v{seed}"
        out_path = os.path.join(OUT_DIR, f"{pid}-{slug}-flux2pro-{variant}.png")
        print(f"\n  [{pid}] Flux 2 Pro seed={seed} (provider: {PROVIDER})...")
        gen_with_provider(
            full_prompt,
            "flux-2-pro",
            out_path,
            w,
            h,
            negative_prompt="",
            seed=seed,
            image_size=aspect,
            num_images=1,
        )


PROMPT_4A = """Somatic Canticles product design catalog page. Top section:
SPEC LOCK: Depict only Somatic Canticles Trilogy Hardcover Set. Exact physical form: Three hardcover volumes — Anamnesis Engine, The Myocardial Chorus, and The Ripening — with deep indigo jackets, Soma Gold foil, and sacred anatomy cover art.. Signature color anchor: Deep Neural Indigo (#1A1F3A). Detail focus: Gold foil glyphs, Tarot numerics, sacred anatomy cover systems, and indigo-to-violet transformations across the trilogy.. Allowed accessories only: three hardcover volumes, annotated sacred anatomy spread, wax-seal brand mark, triangulation-engine diagram sheet, marginalia notebook. Hard bans: robotic hard-surface body. Match the uploaded product reference photos exactly in silhouette, face details, materials, ports, and included accessories.
premium literary trilogy image inside Deep-indigo studio environments, atlas pages, luminous biology, and restrained sacred geometry. Soma Gold (#D4AF37)
light filtering through. Bottom section: technical specification panel with
architectural line drawings in Soma Gold on Deep Neural Indigo background.
Fine hairline technical lines with measurement callouts in Input Mono.
Material swatches panel: deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. High-contrast editorial macro imagery where medical precision meets cosmic luminosity. Deep Neural Indigo 60% backgrounds. Neuronal White 30% text/surfaces. Soma Gold 10% highlights ONLY.
Audience aesthetic: premium literary design, sacred anatomy, hard-SF precision, clinical mysticism. Must feel like it belongs in the world of Tor Books literary SF design, Alex Grey sacred anatomy, Polyvagal Institute, Criterion-grade editorial systems.
8K."""

PROMPT_4B = """Somatic Canticles product collection flat-lay. 5 objects
SPEC LOCK: Depict only Somatic Canticles Trilogy Hardcover Set. Exact physical form: Three hardcover volumes — Anamnesis Engine, The Myocardial Chorus, and The Ripening — with deep indigo jackets, Soma Gold foil, and sacred anatomy cover art.. Signature color anchor: Deep Neural Indigo (#1A1F3A). Detail focus: Gold foil glyphs, Tarot numerics, sacred anatomy cover systems, and indigo-to-violet transformations across the trilogy.. Allowed accessories only: three hardcover volumes, annotated sacred anatomy spread, wax-seal brand mark, triangulation-engine diagram sheet, marginalia notebook. Hard bans: robotic hard-surface body. Match the uploaded product reference photos exactly in silhouette, face details, materials, ports, and included accessories.
arranged on clean surface in precise architectural spacing: three hardcover volumes, annotated sacred anatomy spread, wax-seal brand mark, triangulation-engine diagram sheet, marginalia notebook. Materials:
deep indigo cloth boards, soma gold foil, sacred anatomy linework, anatomical atlas paper, luminous neuronal filaments, wax seal insignia, neural network tracery, cardiac waveform overlays, tarot panel borders, marginalia notebook stock. Overhead composition. Each object casting a single sharp shadow.
Lighting: directional from upper left with warm Soma Gold (#D4AF37)
temperature. Cool Neuronal White (#F5F5F0) fill from below.
No generic new-age clipart, no stock meditation imagery, no pulp-SF tropes, no vague energy effects. High-contrast editorial macro imagery where medical precision meets cosmic luminosity. Deep Neural Indigo 60% backgrounds. Neuronal White 30% text/surfaces. Soma Gold 10% highlights ONLY.
Audience aesthetic: premium literary design, sacred anatomy, hard-SF precision, clinical mysticism. Must feel like it belongs in the world of Tor Books literary SF design, Alex Grey sacred anatomy, Polyvagal Institute, Criterion-grade editorial systems.
8K quality."""

STYLE_ANCHOR = os.path.join(OUT_DIR, "2A-brand-kit-bento-nanobananapro-v1.png")


def main():
    print("=" * 60)
    print(f"{BRAND_NAME} -- Product Photography")
    print("=" * 60)

    anchor_urls = []
    if os.path.exists(STYLE_ANCHOR):
        print("Uploading style anchor...")
        anchor_url = upload_reference(STYLE_ANCHOR)
        if anchor_url:
            anchor_urls = [anchor_url]
    else:
        print("WARNING: Style anchor not found. Run generate-anchor.py first.")

    # Add brand logo reference if available
    logo_url = get_logo_url()
    if logo_url:
        anchor_urls.append(logo_url)
    # Product reference images for model accuracy
    for purl in get_product_ref_urls():
        anchor_urls.append(purl)

    # 4A with composition reference
    print("\n--- 4A: Catalog Layout (Nano Banana Pro) ---")
    urls_4a = list(anchor_urls)
    ref_4a = get_ref_image("4A")
    if ref_4a:
        print(f"  Adding composition ref: {os.path.basename(ref_4a)}")
        ref_url = upload_reference(ref_4a)
        if ref_url:
            urls_4a.append(ref_url)
    urls_4a.extend(get_supp_ref_images("4A"))
    gen_nano_banana("4A", "catalog-layout", PROMPT_4A, "3:4", urls_4a)

    # 4B with composition reference
    print("\n--- 4B: Flatlay (Nano Banana Pro) ---")
    urls_4b = list(anchor_urls)
    ref_4b = get_ref_image("4B")
    if ref_4b:
        print(f"  Adding composition ref: {os.path.basename(ref_4b)}")
        ref_url = upload_reference(ref_4b)
        if ref_url:
            urls_4b.append(ref_url)
    urls_4b.extend(get_supp_ref_images("4B"))
    gen_nano_banana("4B", "flatlay", PROMPT_4B, "1:1", urls_4b)

    print("\n" + "=" * 60)
    print("  PHOTOGRAPHY COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
